path: config/features
name: features.yaml
nb_runs: 50
cat_features:
- B_30_last
- B_38_last
- D_114_last
- D_116_last
- D_117_last
- D_120_last
- D_126_last
- D_63_last
- D_64_last
- D_66_last
- D_68_last
selected_features:
- P_2_last
- P_2_last_round2
- P_2_mean
- P_2_min
- B_9_last_round2
- B_2_last
- B_1_last
- P_2_max
- D_48_last
- B_9_last
- B_1_last_round2
- D_44_last
- D_48_last_round2
- B_11_last_round2
- R_1_mean
- B_2_last_round2
- B_11_last
- R_1_last
- B_18_last_round2
- R_1_last_round2
- B_37_last
- R_1_std
- R_2_last
- D_42_mean
- B_37_last_round2
- B_3_last
- D_42_first
- B_4_last_mean_diff
- P_2_last_mean_diff
- B_3_last_round2
- S_3_mean
- D_41_last_mean_diff
- D_42_max
- P_2_first_round2
- D_44_last_mean_diff
- D_42_min
- R_2_last_mean_diff
- D_41_last
- S_3_last
- D_42_first_round2
- P_2_first
- D_44_mean
- D_39_last
- D_44_max
- D_41_last_round2
- B_3_last_mean_diff
- P_3_mean
- R_1_max
- B_23_last
- B_18_last
- P_3_last
- D_42_last
- B_9_max
- S_3_max
- S_3_last_round2
- D_43_mean
- D_39_last_mean_diff
- D_44_std
- B_4_last
- D_42_last_round2
- B_7_last_round2
- D_39_max
- D_45_mean
- S_8_mean
- R_3_mean
- B_20_last
- S_23_last
- R_6_last_round2
- B_2_mean
- B_7_last
- D_43_last
- D_45_first
- B_22_last
- D_45_max
- S_23_std
- S_25_std
- B_9_mean
- B_4_first_mean_diff
- S_23_last_round2
- S_3_min
- D_61_last_round2
- D_43_last_round2
- B_8_mean
- B_3_std
- B_4_std
- D_55_last_mean_diff
- D_65_last
- R_6_last
- B_23_last_round2
- S_7_last_round2
- B_26_last
- R_1_last_mean_diff
- D_48_last_mean_diff
- D_61_last
- B_3_max
- B_33_last
- D_46_last
- R_3_max
- S_7_mean
- R_2_max
- S_7_last
- B_26_last_round2
- D_46_last_round2
- B_1_mean
- P_3_last_round2
- D_48_max
- D_39_std
- D_45_first_round2
- P_3_min
- B_28_last_mean_diff
- D_50_mean
- R_5_last
- S_7_max
- P_2_first_mean_diff
- S_8_last
- D_50_last
- B_5_last
- B_19_last
- S_15_mean
- S_23_mean
- B_3_mean
- R_2_mean
- R_27_min
- D_61_mean
- B_25_last
- B_30_last
- R_10_std
- D_45_last_round2
- R_27_mean
- R_6_mean
- B_8_min
- D_45_min
- B_11_last_mean_diff
- D_43_max
- D_75_last
- R_3_last
- D_46_mean
- D_45_last
- S_23_last_mean_diff
- B_8_first
- D_112_last_round2
- R_7_last_round2
- D_65_std
- D_49_last
- D_62_mean
- D_48_min
- R_4_last
- D_50_max
- D_41_max
- R_27_last
- B_5_mean
- D_65_mean
- B_38_last
- B_5_last_round2
- R_6_max
- P_2_std
- D_41_first_mean_diff
- B_4_max
- R_5_mean
- B_11_mean
- R_27_max
- D_55_last
- B_37_last_mean_diff
- R_16_std
- R_4_last_mean_diff
- B_6_last
- D_43_min
- B_9_last_mean_diff
- D_54_last_mean_diff
- R_7_mean
- D_54_last
- D_65_last_mean_diff
- D_50_first
- B_22_mean
- S_7_min
- R_16_mean
- D_48_mean
- D_132_max
- S_3_std
- D_65_first_mean_diff
- D_56_mean
- D_132_min
- S_23_max
- D_65_max
- B_37_mean
- S_8_max
- B_8_last
- D_44_first_mean_diff
- D_50_last_round2
- B_23_std
- B_8_last_round2
- S_25_min
- D_51_mean
- D_41_diff1
- S_25_mean
- D_58_last
- R_27_last_round2
- B_1_last_mean_diff
- D_75_std
- D_50_first_round2
- D_62_min
- D_39_diff1
- S_3_first
- R_11_mean
- B_23_last_mean_diff
- D_56_min
- D_56_last
- D_53_last
- D_59_std
- D_42_last_mean_diff
- D_50_min
- D_41_std
- B_8_std
- B_2_min
- D_132_first
- B_10_last
- S_25_last
- R_2_std
- R_11_std
- D_61_max
- D_52_first
- R_4_mean
- D_56_last_round2
- D_42_std
- D_54_last_round2
- D_52_min
- B_26_last_mean_diff
- D_56_first
- R_4_max
- D_58_last_round2
- B_1_max
- D_49_std
- B_3_first_mean_diff
- B_40_mean
- D_132_last
- B_4_mean
- B_40_last_round2
- R_7_std
- S_13_last
- D_132_mean
- D_56_max
- R_1_first_mean_diff
- B_25_last_round2
- D_132_last_round2
- B_7_mean
- D_43_std
- D_55_last_round2
- D_43_first
- B_26_mean
- R_6_last_mean_diff
- S_15_max
- D_56_first_round2
- B_10_last_round2
- D_132_first_round2
- B_8_first_round2
- R_5_last_mean_diff
- R_3_min
- B_5_max
- D_49_last_mean_diff
- B_26_max
- B_17_last_round2
- B_14_last
- S_25_last_round2
- B_28_first_mean_diff
- B_28_std
- D_79_last
- D_55_std
- B_7_last_mean_diff
- D_74_std
- B_25_last_mean_diff
- R_10_max
- R_10_mean
- D_47_last
- R_3_std
- S_23_first_mean_diff
- D_58_max
- B_12_last
- D_131_last
- D_75_last_mean_diff
- D_106_std
- S_8_min
- D_74_max
- B_14_last_mean_diff
- D_54_min
- R_8_std
- B_11_min
- D_75_mean
- D_50_diff1
- S_25_first_mean_diff
- S_3_first_round2
- R_5_max
- D_112_last_mean_diff
- B_7_max
- D_43_first_round2
- R_27_first
- B_23_max
- D_74_last_mean_diff
- D_75_max
- D_47_mean
- B_26_std
- D_84_last
- S_7_std
- D_59_last_mean_diff
- S_22_last
- R_7_last
- D_129_last
- B_22_max
- D_49_max
- B_11_max
- R_4_std
- D_59_first_mean_diff
- D_51_max
- D_49_mean
- D_74_last
- B_18_min
- D_52_last_round2
- B_6_last_round2
- B_11_diff1
- D_50_std
- D_39_mean
- D_77_min
- D_128_last_round2
- S_22_last_round2
- R_6_std
- D_46_max
- B_18_last_mean_diff
- B_14_last_round2
- D_47_last_round2
- D_48_first_mean_diff
- B_12_max
- D_62_first
- D_51_last
- B_21_std
- D_52_last
- D_52_mean
- S_26_std
- B_23_mean
- D_77_mean
- D_42_first_mean_diff
- D_41_mean
- D_131_std
- D_46_min
- D_128_min
- D_128_last
- B_37_max
- D_79_last_mean_diff
- D_55_diff1
- D_47_min
- B_19_last_mean_diff
- D_53_last_mean_diff
- B_37_min
- D_91_mean
- D_106_last_mean_diff
- D_47_first
- P_3_last_mean_diff
- R_8_max
- S_15_last
- D_84_mean
- S_26_max
- R_15_mean
- B_12_mean
- D_129_mean
- D_49_first_mean_diff
- D_84_last_mean_diff
- B_37_diff1
- D_120_last
- D_74_mean
- D_53_std
- B_33_mean
- B_3_min
- D_62_max
- B_17_last
- D_77_first
- D_131_last_round2
- B_7_std
- D_55_first_mean_diff
- B_8_max
- S_25_last_mean_diff
- S_23_diff1
- D_50_last_mean_diff
- R_5_std
- S_16_mean
- D_132_diff1
- B_1_min
- D_58_mean
- R_7_max
- D_54_std
- B_18_mean
- D_129_max
- B_12_min
- B_40_last
- P_3_std
- D_65_diff1
- P_3_max
- B_21_mean
- D_128_max
- D_106_first_mean_diff
- D_110_mean
- B_28_last
- D_78_std
- B_3_diff1
- D_132_first_mean_diff
- D_128_mean
- S_24_max
- D_50_first_mean_diff
- D_62_last
- D_46_first
- B_5_min
- D_131_max
- B_22_last_mean_diff
- D_106_last
- D_53_last_round2
- D_61_last_mean_diff
- R_27_first_round2
- S_24_last
- B_28_diff1
- D_70_std
- D_78_last
- B_37_first_mean_diff
- D_131_mean
- S_12_last
- D_84_std
- B_10_mean
- B_9_diff1
- B_25_diff1
- B_11_std
- B_17_mean
- S_16_std
- S_24_last_round2
- B_40_std
- S_3_first_mean_diff
- D_106_mean
- B_23_first_mean_diff
- S_24_last_mean_diff
- D_52_max
- D_53_diff1
- S_22_last_mean_diff
- B_9_std
- D_52_first_round2
- B_5_std
- D_54_diff1
- D_47_max
- D_128_std
- B_38_count
- B_3_first
- B_7_first_mean_diff
- D_129_min
- B_26_first_mean_diff
- B_13_max
- S_9_min
- D_110_last
- D_128_first
- S_13_min
- D_78_max
- B_9_min
- B_6_min
- R_16_first_mean_diff
- B_12_last_round2
- D_55_max
- D_106_max
- D_74_first_mean_diff
- D_128_first_round2
- R_3_first
- D_132_last_mean_diff
- S_26_mean
- R_14_mean
- D_119_max
- D_110_first_round2
- D_78_mean
- B_39_diff1
- B_1_std
- D_58_std
- D_118_first_round2
- B_30_count
- S_5_last_round2
- D_132_std
- D_51_first
- S_7_first
- R_10_last
- B_1_diff1
- B_12_last_mean_diff
- D_110_first
- D_70_max
- D_56_std
- S_15_min
- B_23_min
- D_79_std
- D_75_first_mean_diff
- R_14_max
- S_6_mean
- D_48_first
- S_7_first_round2
- D_110_min
- R_27_std
- D_110_max
- B_19_mean
- B_33_last_mean_diff
- D_118_mean
- B_21_last
- R_16_max
- D_77_max
- S_26_last_round2
- B_1_first_mean_diff
- D_53_mean
- D_110_diff1
- B_39_first
- B_19_max
- D_70_last
- B_10_min
- D_129_first
- S_26_last
- S_16_max
- D_122_mean
- D_53_first
- D_47_first_round2
- D_54_first_mean_diff
- D_60_last_round2
- D_130_std
- P_3_first
- D_55_mean
- D_58_diff1
- B_39_mean
- B_22_std
- B_39_first_mean_diff
- R_15_first_mean_diff
- P_2_diff1
- D_84_max
- D_112_first_mean_diff
- B_39_last_round2
- B_26_diff1
- R_2_first_mean_diff
- B_5_last_mean_diff
- D_48_diff1
- B_21_max
- B_6_mean
- B_21_first_mean_diff
- D_46_first_round2
- D_58_last_mean_diff
- D_110_last_round2
- P_4_min
- B_36_mean
- S_5_last
- R_10_first_mean_diff
- S_22_max
- B_39_last_mean_diff
- D_56_last_mean_diff
- S_25_diff1
- S_9_mean
- D_55_first_round2
- B_7_diff1
- B_19_std
- B_20_first_mean_diff
- B_14_first_mean_diff
- D_59_last
- D_118_last_round2
- B_13_mean
- D_44_first
- B_4_min
- S_13_max
- D_79_max
- D_121_min
- B_36_last
- S_26_first_mean_diff
- D_54_mean
- R_21_mean
- B_7_min
- B_17_first_round2
- D_121_first_mean_diff
- D_53_max
- B_28_last_round2
- B_2_max
- B_9_first
- D_131_diff1
- D_56_first_mean_diff
- D_142_last_round2
- B_19_first_mean_diff
- S_22_mean
- S_3_last_mean_diff
- D_91_max
- R_8_mean
- D_119_first_round2
- P_3_first_round2
- D_64_last
- B_2_last_mean_diff
- P_4_last_round2
- D_112_last
- B_20_mean
- D_44_min
- D_115_mean
- R_8_first_mean_diff
- B_12_std
- D_112_min
- B_5_first
- B_39_min
- S_5_max
- D_46_std
- B_28_max
- S_5_mean
- S_9_max
- B_24_mean
- B_28_first_round2
- B_20_min
- R_7_last_mean_diff
- B_18_first_mean_diff
- D_116_count
- B_14_max
- S_20_mean
- B_3_first_round2
- S_3_diff1
- R_26_last
- P_3_diff1
- S_16_last_round2
- S_13_mean
- D_130_last
- S_11_max
- D_119_mean
- S_7_first_mean_diff
- D_81_max
- D_45_last_mean_diff
- D_71_last_round2
- D_61_diff1
- D_142_max
- D_71_mean
- D_78_first_mean_diff
- D_76_first_round2
- R_26_mean
- B_40_max
- D_118_min
- D_122_last_mean_diff
- D_131_last_mean_diff
- B_25_first_mean_diff
- S_9_last
- D_71_max
- D_83_std
- D_105_max
- R_2_diff1
- R_15_std
- D_84_first_mean_diff
- S_9_first
- R_26_max
- P_4_std
- D_131_first_round2
- S_20_std
- B_16_mean
- S_15_first
- D_52_last_mean_diff
- D_72_mean
- D_63_count
- D_77_first_round2
- B_40_last_mean_diff
- B_6_diff1
- D_142_first_mean_diff
- D_66_last
- B_14_std
- S_7_last_mean_diff
- D_118_std
- B_40_first_mean_diff
- S_8_first
- D_144_std
- D_121_last
- B_25_max
- D_62_last_round2
- R_1_min
- S_25_first
- R_20_last_mean_diff
- D_111_last
- D_111_mean
- S_5_std
- R_10_last_mean_diff
- P_3_first_mean_diff
- R_12_last
- R_11_last
- D_141_mean
- S_7_diff1
- D_130_first_mean_diff
- D_53_first_mean_diff
- D_78_last_mean_diff
- B_36_std
- D_119_last
- R_5_diff1
- B_14_diff1
- B_4_diff1
- B_11_first_round2
- S_25_max
- D_126_count
- B_12_first_mean_diff
- B_21_last_round2
- B_5_diff1
- D_61_std
- D_73_min
- S_11_mean
- R_3_last_mean_diff
- R_21_last
- D_136_last_mean_diff
- B_20_max
- B_16_last
- D_61_min
- D_48_first_round2
- B_10_max
- R_6_first_mean_diff
- B_20_last_mean_diff
- D_77_last
- P_4_first
- B_30_nunique
- B_17_min
- R_7_first_mean_diff
- P_4_max
- P_4_mean
- B_17_last_mean_diff
- D_75_min
- R_5_first_mean_diff
- B_9_first_mean_diff
- D_77_last_round2
- D_62_first_round2
- P_4_first_round2
- R_15_max
- R_4_first_mean_diff
- B_9_first_round2
- D_112_mean
- R_1_diff1
- B_18_max
- D_55_min
- B_17_diff1
- B_33_min
- B_11_first_mean_diff
- B_22_first_mean_diff
- D_112_std
- D_61_first
- D_61_first_round2
- B_2_std
- D_56_diff1
- B_16_max
- B_6_last_mean_diff
- R_13_max
- B_16_last_mean_diff
- R_7_diff1
- D_58_first_mean_diff
- B_40_min
- B_33_max
- B_6_max
- D_48_std
- B_2_first_mean_diff
- R_8_last
- R_6_diff1
- B_17_max
- S_15_std
- P_4_last
- B_20_std
- R_13_std
- B_37_std
- B_33_std
- R_26_first
- B_16_first_mean_diff
- B_33_first_mean_diff
- R_26_min
- D_74_min
- D_112_diff1
- D_60_last
- B_19_min
- R_13_mean
- D_53_min
- R_8_last_mean_diff
- R_16_last_mean_diff
- D_61_first_mean_diff
- D_79_mean
- D_70_mean
- S_27_last_round2
- D_53_first_round2
- B_10_last_mean_diff
- D_58_min
- B_17_std
- D_59_max
- D_39_first_mean_diff
- S_27_last
- D_114_last
- R_10_diff1
- D_91_first
- D_91_min
- B_5_first_mean_diff
- D_44_diff1
- B_12_first
- B_25_mean
- B_25_min
- D_59_mean
- D_81_last
- R_1_first_round2
- B_18_diff1
- B_2_first_round2
- B_23_diff1
- R_1_first
- D_72_max
- B_16_min
- D_72_std
- R_13_first_mean_diff
- R_21_max
- D_51_std
- D_72_last
- B_20_diff1
- D_43_first_mean_diff
- R_11_max
- D_55_first
- D_43_diff1
- D_79_first_mean_diff
- B_14_mean
- D_75_first
- D_62_std
- S_27_min
- D_43_last_mean_diff
- B_17_first
- B_2_first
- R_8_diff1
- D_123_first
- B_28_mean
- S_24_mean
- D_74_first
- D_125_min
- R_11_first_mean_diff
- D_125_first
- B_11_first
- D_115_last
- P_4_first_mean_diff
- B_22_min
- D_81_mean
- D_81_last_mean_diff
- B_1_first
- B_17_first_mean_diff
- D_124_first
- D_113_min
- B_18_first
- D_118_max
- D_115_last_round2
- D_58_first
- D_89_max
- B_16_std
- D_58_first_round2
- D_51_min
- D_70_last_mean_diff
- B_7_first_round2
- D_122_min
- D_123_min
- R_3_first_mean_diff
- D_83_min
- D_118_first
- B_19_diff1
- S_23_min
- B_10_first
- B_18_std
- S_27_max
- D_133_std
- R_14_std
- D_133_max
- B_6_first
- D_123_std
- D_134_min
- R_15_last_mean_diff
- D_134_last
- D_134_max
- B_8_diff1
- B_37_first
- B_22_first
- S_27_std
- S_5_last_mean_diff
- D_70_first_mean_diff
- P_4_last_mean_diff
- R_13_last
- R_20_mean
- D_131_first_mean_diff
- D_134_last_mean_diff
- R_21_std
- D_122_first
- B_12_first_round2
- D_112_max
- D_118_last
- R_9_mean
- D_119_last_round2
- D_115_max
- D_59_diff1
- R_9_max
- B_14_min
- D_115_min
- D_113_first
- D_111_max
- S_13_last_mean_diff
- B_1_first_round2
- D_115_first_round2
- D_59_first
- D_78_diff1
- B_10_std
- D_134_mean
- B_23_first_round2
- D_51_first_mean_diff
- R_24_std
- B_13_last
- D_119_first
- B_20_first
- D_133_mean
- D_127_max
- D_134_first
- B_5_first_round2
- B_40_first_round2
- B_6_first_mean_diff
- B_13_last_round2
- D_89_mean
- R_20_max
- B_33_first
- R_4_diff1
- S_13_std
- D_68_count
- B_6_first_round2
- R_16_last
- B_25_std
- R_11_last_mean_diff
- B_27_max
- D_127_mean
- R_20_std
- S_22_first
- B_4_first
- S_22_min
- B_39_last
- R_24_max
- D_134_first_round2
- R_2_first
- D_59_min
- D_134_first_mean_diff
- D_76_mean
- S_22_first_round2
- B_8_first_mean_diff
- D_71_last
- S_23_first_round2
- R_24_mean
- D_124_min
- D_110_last_mean_diff
- D_115_first
- D_122_last
- S_11_min
- B_38_nunique
- D_89_std
- S_24_min
- D_76_last
- S_16_first_mean_diff
- D_134_last_round2
- B_13_min
- B_37_first_round2
- B_28_min
- B_18_first_round2
- D_133_last_round2
- D_83_first_mean_diff
- D_41_min
- B_19_first
- D_72_last_mean_diff
- B_8_last_mean_diff
- B_16_first
- B_36_last_round2
- R_17_std
- D_119_min
- S_27_last_mean_diff
- D_76_min
- B_16_diff1
- D_136_std
- B_7_first
- B_24_max
- B_24_std
- D_110_first_mean_diff
- D_133_last
- S_23_first
- D_46_first_mean_diff
- D_135_max
- D_46_last_mean_diff
- B_15_last
- B_15_last_mean_diff
- B_24_last
- D_136_mean
- S_20_max
- D_83_first
- B_39_first_round2
- R_13_last_mean_diff
- B_15_max
- D_76_max
- D_60_last_mean_diff
- B_2_diff1
- D_81_std
- S_5_first_mean_diff
- S_16_last
- B_24_last_round2
- D_127_std
- B_23_first
- R_6_first
- D_138_std
- D_66_count
- S_25_first_round2
- D_116_nunique
- B_39_max
- R_6_first_round2
- B_36_max
- D_51_last_mean_diff
- D_125_std
- D_130_last_round2
- B_21_last_mean_diff
- D_137_mean
- D_70_min
- R_17_mean
- D_121_last_round2
- R_12_min
- D_76_first
- S_24_first_round2
- D_81_first_mean_diff
- D_62_first_mean_diff
- D_83_last_mean_diff
- R_21_first_mean_diff
- D_121_max
- D_135_std
- B_40_diff1
- B_10_first_round2
- B_39_std
- B_10_first_mean_diff
- D_120_count
- S_8_std
- D_71_last_mean_diff
- D_68_last
- D_130_max
- LT
- R_9_last
- D_136_max
- D_71_min
- S_24_first_mean_diff
- R_17_max
- R_12_last_round2
- D_68_nunique
- D_89_last
- D_111_std
- R_12_std
- D_73_first_round2
- D_60_max
- B_14_first
- D_137_max
- D_60_mean
- D_135_mean
- D_121_first
- D_137_std
- R_20_last
- D_41_first_round2
- D_62_diff1
- D_134_std
- S_6_first_mean_diff
- R_17_first_mean_diff
- S_9_std
- S_5_min
- D_89_first_mean_diff
- R_12_mean
- D_73_first
- S_24_first
- D_128_diff1
- D_41_first
- B_10_diff1
- B_12_diff1
- D_113_max
- D_138_max
- R_21_last_mean_diff
- B_15_last_round2
- S_22_std
- D_84_diff1
- R_9_std
- B_13_first
- R_7_first
- D_138_mean
- D_122_max
- D_121_mean
- D_72_first
- S_22_first_mean_diff
- D_113_mean
- D_130_mean
- D_60_min
- D_110_std
- B_25_first
- S_11_std
- S_6_last_mean_diff
- S_27_mean
- R_4_first
- D_76_first_mean_diff
- D_92_mean
- R_19_last
- B_15_std
- D_69_std
- R_27_last_mean_diff
- D_91_last_mean_diff
- D_113_std
- B_40_first
- R_24_last_mean_diff
- D_60_first_round2
- B_14_first_round2
- D_45_std
- S_6_std
- S_9_first_round2
- D_70_first
- D_76_last_round2
- S_27_first_mean_diff
- D_82_mean
- D_73_last_round2
- D_111_last_mean_diff
- S_9_last_round2
- D_71_first_round2
- B_15_mean
- D_131_first
- B_6_std
- D_69_first_round2
- D_73_first_mean_diff
- D_112_first_round2
- R_9_first
- D_73_last_mean_diff
- D_75_diff1
- D_124_std
- D_76_last_mean_diff
- D_54_first
- B_27_last
- D_76_std
- D_133_first_mean_diff
- R_14_last_round2
- D_144_first_mean_diff
- D_114_count
- B_13_first_round2
- S_16_last_mean_diff
- R_13_diff1
- B_13_first_mean_diff
- D_112_first
- D_62_last_mean_diff
- S_5_first
- D_128_first_mean_diff
- D_60_first_mean_diff
- R_16_first
- R_11_first
- S_13_first_mean_diff
- R_27_first_mean_diff
- D_74_diff1
- R_25_std
- S_26_first
- B_22_diff1
- D_46_diff1
- D_89_last_mean_diff
- R_15_last
- D_60_diff1
- S_26_diff1
- D_117_count
- R_27_diff1
- D_42_diff1
- S_24_std
- D_73_mean
- B_25_first_round2
- D_72_min
- S_26_last_mean_diff
- S_12_std
- B_24_last_mean_diff
- D_82_max
- D_131_min
- D_72_first_mean_diff
- D_124_last_mean_diff
- B_28_first
- D_113_last_mean_diff
- D_91_last
- R_26_std
- B_15_min
- D_73_std
- S_9_last_mean_diff
- R_14_first_mean_diff
- D_128_last_mean_diff
- D_123_first_mean_diff
- S_26_min
- S_26_first_round2
- D_121_first_round2
- D_77_std
- S_6_min
- B_26_first_round2
- B_15_first_round2
- D_83_mean
- B_13_last_mean_diff
- R_17_last
- D_69_min
- R_17_last_mean_diff
- S_9_diff1
- S_13_first
- B_24_first_mean_diff
- D_71_std
- D_133_last_mean_diff
- S_6_last
- S_20_first_mean_diff
- R_24_last
- D_111_first_mean_diff
- R_22_last_mean_diff
- D_120_nunique
- D_130_last_mean_diff
- S_8_last_mean_diff
- D_121_diff1
- D_88_max
- D_71_first
- R_16_diff1
- D_84_first
- D_73_last
- B_36_first_mean_diff
- B_13_std
- D_138_last
- D_64_count
- D_77_last_mean_diff
- D_69_last
- D_65_first
- R_7_first_round2
- D_69_first
- B_15_first
- D_115_diff1
- D_82_last
- S_12_min
- S_22_diff1
- S_8_first_mean_diff
- D_80_std
- D_144_first
- D_123_last_mean_diff
- D_91_first_mean_diff
- D_88_mean
- B_15_first_mean_diff
- D_122_std
- D_118_diff1
- D_39_min
- D_88_first_mean_diff
- D_108_std
- D_82_min
- D_144_mean
- D_82_first
- R_9_min
- D_117_last
- D_123_mean
- D_78_first
- D_88_min
- S_6_max
- D_102_mean
- D_115_std
- D_77_first_mean_diff
- R_25_last
- D_127_first
- B_31_last_mean_diff
- S_20_last
- R_9_last_mean_diff
- S_27_first_round2
- S_20_last_mean_diff
- B_36_last_mean_diff
- B_27_std
- S_13_diff1
- D_80_last
- D_139_last_mean_diff
- D_71_diff1
- B_41_first_mean_diff
- D_73_max
- R_24_first_mean_diff
- R_12_first_mean_diff
- R_3_diff1
- D_121_last_mean_diff
- R_25_mean
- S_19_max
- D_88_std
- B_21_first_round2
- D_92_last
- R_14_last
- D_121_std
- D_54_max
- D_39_first
- D_88_first_round2
- B_41_std
- R_16_min
- D_129_std
- D_88_last_round2
- S_12_last_round2
- D_88_last_mean_diff
- B_21_first
- R_2_min
