path: config/features
name: features.yaml
threshold: 0.4
selected_features:
- B_11-P_2_mean
- P_2_last
- B_1_last
- P_2_last_round2
- D_39_last
- B_4_last
- S_3_mean
- B_2_last
- R_1_last
- B_5_last
- B_3_std
- B_4_std
- B_7_last
- S_3_last
- D_44_last
- D_112_std
- D_42_mean
- D_46_last
- D_64_last
- D_112_last
- D_62_mean
- D_43_mean
- D_62_min
- D_45_max
- B_11_last
- D_51_min
- D_50_last
- D_43_last
- R_2_last
- D_42_min
- D_66_last
- D_50_max
- B_3_last
- B_3_last_round2
- B_9_last
- S_26_max
- D_49_last
- S_15_mean
- D_41_last
- D_39_max
- B_18_last
- B_1_last_round2
- D_46_mean
- D_51_mean
- R_1_last_round2
- D_48_last_round2
- D_41_last_round2
- R_1_std
- B_9_last_round2
- S_12_std
- D_131-P_3_mean
- D_131-P_2_mean
- S_23_last_round2
- B_18_last_round2
- R_1_mean
- R_27_min
- D_51_last
- B_11_last_round2
- D_59_max
- S_26_mean
- B_2_last_round2
- S_9_min
- D_118_min
- R_3_mean
- D_48_last
- R_5_last
- B_5_min
- S_11_max
- S_11_mean
- D_42_max
- S_24_last
- D_76_last
- S_16-P_2_std
- S_9_mean
- D_45_mean
- R_11_last
- B_17_last
- B_7_last_round2
- D_44_std
- D_50_mean
- D_56_min
- B_2_mean
- S_8_mean
- S_3_min
- S_9_last
- D_47_last
- D_129_mean
- D_121_min
- D_123_max
- R_3_last
- S_5_last
- D_59_std
- D_56_last
- D_120_last
- D_114_last
- D_43_last_round2
- D_54_last
- D_49_std
- B_14-P_2_mean
- D_62_last
- D_46_min
- R_11_mean
- B_40_std
- B_7_std
- B_18_min
- B_22_last
- D_47_max
- R_4_last
- B_17_last_round2
- D_52_last
- R_7_last
- D_46_last_round2
- D_129_last
- D_65_max
- D_65_mean
- S_12_mean
- D_117_last
- B_10_last_round2
- S_3_last_round2
- D_39-P_3_std
- S_23_last
- B_10_std
- S_7_last
- D_52_min
- B_11-P_2_std
- B_23_last
- D_121_max
- R_27_last
- D_47_mean
- D_128_max
- P_2_min
- S_26_last
- D_105_max
- D_123_std
- S_25_std
- D_39_std
- P_2_mean
- D_82_mean
- D_144_std
- D_52_mean
- P_2_max
- S_22_std
- D_65_std
- S_11_last
- D_60_last_round2
- B_8_mean
- D_77_mean
- S_5_max
- B_29_last
- B_14_last
- B_29_min
- B_29_max
- S_15_max
- S_12_min
- D_119_min
- D_91_min
- B_5_last_round2
- B_5_mean
- D_75_std
- D_77_last
- B_14-P_2_std
- P_3_max
- S_16-P_3_std
- B_40_max
- D_77_max
- S_23-P_3_std
- B_17-P_3_mean
- B_14_last_round2
- S_7_mean
- B_9_mean
- D_102_max
- B_18_mean
- B_29_mean
- S_16-P_3_mean
- D_71_last_round2
- D_44_max
- B_2_min
- D_45_last_round2
- B_37_std
- D_43_max
- D_39-P_2_std
- P_3_last
- D_63_last
- D_60_last
- D_71_last
- B_24_last_round2
- D_121_mean
- S_26_std
- S_7_min
- S_16-P_2_mean
- B_15_mean
- D_56_mean
- D_53_last
- S_9_std
- B_5_max
- D_133_max
- S_8_last
- S_3_max
- D_82_last
- D_77_min
- B_17_mean
- D_45_last
- R_3_max
- B_20_last
- D_65_last
- S_8_max
- S_5_std
- D_122_mean
- B_37_last_round2
- S_9_max
- S_23_std
- S_23-P_2_std
- B_20_mean
- S_16_max
- B_5_std
- D_112_mean
- B_15_max
- D_39-P_2_mean
- S_24_max
- D_46_max
- B_23_last_round2
- D_55_std
- B_17_min
- R_7_last_round2
- D_121_last
- D_124_last
- D_122_max
- D_47_min
- D_70_mean
- D_115_max
- D_131-P_3_std
- R_26_max
- S_22_mean
- D_43_min
- B_8_min
- D_56_max
- B_13_mean
- B_28_min
- D_76_mean
- D_76_min
- D_132_last
- S_22_last
- B_37_min
- B_3_mean
- D_48_std
- D_124_mean
- B_17-P_2_mean
- D_61_mean
- B_37_last
- S_9_last_round2
- B_33_mean
- D_42_last
- D_102_std
- D_141_max
- B_12_last_round2
- D_140_last
- B_26_last_round2
- B_1_max
- D_41_std
- D_118_mean
- D_132_max
- D_132_mean
- S_5_last_round2
- D_43_std
- S_23-P_2_mean
- D_125_std
- B_40_last_round2
- D_122_last
- D_113_max
- D_142_std
- S_24_last_round2
- D_110_max
- D_61_min
- D_53_last_round2
- B_6_min
- B_2_std
- D_118_max
- S_15_min
- B_22_mean
- D_91_mean
- P_3_last_round2
- B_9_std
- D_61_std
- S_24_std
- R_12_last
- R_10_last
- D_70_max
- D_70_last
- D_45_min
- B_26_max
- D_123_mean
- D_124_max
- S_24_min
- B_10_min
- B_15_last
- D_55_mean
- S_23_mean
- D_63_nunique
- B_21_mean
- S_6_mean
- D_141_std
- D_132_min
- S_25_last
- B_39_min
- R_26_last
- B_28_mean
- B_14_std
- B_26_last
- D_69_last_round2
- S_7_std
- B_10_last
- B_10_max
- D_53_std
- R_16_mean
- B_13_max
- B_26_std
- B_17-P_3_std
- D_72_std
- R_8_last
- B_21_max
- B_9_max
- S_25_max
- S_6_std
- B_11-P_3_std
- B_36_mean
- B_11-P_3_mean
- B_15_last_round2
- S_16_mean
- B_12_max
- R_6_max
- D_55_min
- D_142_last
- D_134_min
- D_47_last_round2
- B_21_last_round2
- B_14_min
- R_9_min
- S_5_mean
- D_106_last
- B_16_min
- B_11_std
- D_52_max
- D_145_mean
- B_25_mean
- B_2_max
- B_16_std
- B_40_mean
- D_48_min
- D_49_max
- S_15_last
- D_60_mean
- B_3_max
- R_9_mean
- B_9_min
- B_14-P_3_mean
- R_27_std
- D_80_last
- D_141_mean
- B_23_mean
- S_13_max
- B_19_std
- B_18_std
- D_119_last
- B_17-P_2_std
- B_33_std
- D_48_max
- D_61_last
- D_72_mean
- B_26_mean
- D_71_mean
- D_91_last
- D_118_last
- S_12_max
- D_115_std
- D_126_nunique
- D_79_last
- D_74_max
- R_16_std
- B_12_mean
- D_119_mean
- D_73_min
- D_108_mean
- D_131-P_2_std
- D_142_max
- D_133_mean
- D_83_last
- S_12_last_round2
- D_133_last_round2
- S_27_mean
- R_1_max
- D_128_mean
- B_40_min
- D_70_std
- R_26_mean
- D_58_std
- D_141_min
- D_54_min
- B_14-P_3_std
- D_59_mean
- D_46_std
- D_105_min
- D_91_std
- B_25_min
- D_39-P_3_mean
- B_15_std
- B_40_last
- D_134_mean
- B_20_max
- S_25_mean
- D_115_last
- S_23_max
- S_19_max
- D_61_max
- D_139_mean
- S_22_max
- D_140_mean
- D_112_max
- D_134_std
- D_58_min
- S_24_mean
- D_131_last
- B_14_mean
- D_48_mean
- S_7_last_round2
- D_39_mean
- R_11_std
- D_108_std
- R_14_max
- R_5_std
- D_144_last
- B_37_mean
- D_129_std
- D_55_last
- D_107_std
- B_41_mean
- B_11_mean
- D_53_mean
- D_134_max
- D_142_mean
- B_6_last_round2
- R_26_std
- D_111_std
- S_23-P_3_mean
- R_6_mean
- B_14_max
- B_15_min
- D_58_last_round2
- B_10_mean
- D_77_std
- R_6_std
- D_104_max
- D_41_mean
- D_119_max
- B_21_std
- S_16_last
- B_21_min
- B_29_std
- D_61_last_round2
- D_71_std
- B_39_std
- D_42_last_round2
- P_4_min
- S_25_last_round2
- D_111_mean
- S_20_std
- B_11_min
- D_54_mean
- D_69_last
- R_20_last
- D_111_max
- D_133_std
- D_110_mean
- R_6_min
- D_53_max
- B_7_min
- D_69_min
- D_60_std
- B_36_std
- B_28_std
- D_137_std
- D_134_last_round2
- D_62_std
- D_80_std
- R_7_std
- R_14_std
- D_104_min
- D_76_max
- S_12_last
- S_27_std
- D_76_std
- B_27_mean
- S_16_last_round2
- S_7_max
- D_127_std
- S_22_min
- S_19_std
- D_74_std
- B_31_std
- B_7_mean
- B_21_last
- B_8_std
- B_24_mean
- D_88_std
- R_14_mean
- D_131_std
- P_3_mean
- B_12_min
- B_26_min
- B_41_std
- D_69_std
- D_69_max
