path: config/features
name: features.yaml
selected_features:
- P_2_last
- B_1_last
- D_39_last
- S_3_mean
- B_4_last
- B_2_last
- B_3_std
- R_1_last
- B_4_std
- B_9_last
- D_41_last
- S_3_last
- B_7_last
- B_5_last
- B_3_last
- B_18_last
- D_62_mean
- D_43_mean
- D_43_last
- R_1_mean
- D_46_last
- D_44_last
- D_48_last
- D_64_last
- R_2_last
- S_26_max
- P_2_mean
- D_50_max
- S_23_last
- D_42_min
- D_51_last
- D_49_last
- B_2_mean
- D_51_mean
- D_112_last
- D_59_max
- D_62_min
- R_1_std
- S_11_mean
- D_42_first
- B_11_last
- D_48_rate_last
- R_27_min
- D_45_max
- D_66_last
- D_41_rate_first
- D_39_max
- D_51_min
- B_7_mean
- S_26_mean
- S_12_std
- B_29_first
- D_47_mean
- B_5_min
- D_42_mean
- P_3_std
- B_29_min
- S_9_mean
- S_15_mean
- D_48_diff_last
- R_3_mean
- D_39_std
- B_9_diff_last
- B_7_std
- D_46_first
- D_112_std
- S_9_min
- D_50_last
- R_5_last
- B_10_last
- D_46_mean
- D_123_first
- B_4_diff_last
- D_59_std
- D_45_mean
- B_17_first
- D_76_last
- D_118_first
- B_14_last
- D_60_last
- P_2_std
- D_121_min
- R_11_last
- R_4_last
- S_8_mean
- B_18_min
- D_129_mean
- D_49_std
- R_3_last
- D_45_first
- D_65_mean
- B_21_max
- S_11_max
- B_29_max
- D_50_mean
- D_129_last
- S_24_last
- D_120_last
- B_17_last
- S_12_mean
- D_65_std
- S_9_last
- D_62_last
- D_44_std
- B_22_last
- S_9_std
- D_118_min
- D_122_mean
- P_3_mean
- S_15_max
- S_3_min
- S_5_last
- D_54_last
- D_52_min
- D_114_last
- B_29_last
- D_117_last
- B_29_mean
- D_144_std
- D_44_max
- D_42_max
- B_23_last
- D_56_first
- R_7_last
- D_132_mean
- D_121_first
- B_40_max
- D_65_max
- P_3_last
- D_56_max
- B_7_rate_last
- B_2_min
- B_10_min
- S_25_std
- B_14_std
- B_15_mean
- B_18_mean
- D_61_diff_last
- P_2_max
- B_28_first
- D_47_last
- D_53_last
- S_7_last
- B_3_diff_last
- D_77_mean
- P_2_min
- S_8_last
- P_3_max
- D_124_last
- S_13_max
- B_9_mean
- B_8_mean
- B_25_last
- D_77_first
- R_11_mean
- B_9_rate_last
- D_91_min
- S_24_max
- S_12_min
- B_5_mean
- S_9_first
- D_71_last
- S_8_max
- D_56_last
- D_132_max
- S_3_max
- D_52_last
- S_26_first
- D_119_first
- D_75_std
- D_56_min
- S_5_max
- S_22_last
- D_52_mean
- B_28_min
- S_7_mean
- B_24_last
- S_7_diff_last
- R_27_first
- B_4_rate_last
- B_37_std
- R_27_last
- D_45_min
- B_17_mean
- D_50_first
- D_128_max
- B_5_std
- B_40_std
- D_55_std
- D_142_std
- R_12_last
- S_22_first
- D_105_first
- S_11_last
- D_46_min
- D_102_first
- B_20_last
- D_112_min
- B_9_first
- D_45_last
- B_37_last
- B_5_max
- D_43_first
- D_121_max
- B_10_mean
- R_26_last
- D_128_mean
- D_48_rate_first
- D_46_diff_last
- D_105_max
- S_26_last
- D_46_rate_last
- D_47_max
- S_24_min
- D_43_min
- B_10_std
- D_121_mean
- D_122_last
- S_24_std
- S_7_max
- P_3_min
- D_44_mean
- R_9_first
- D_123_std
- D_75_last
- B_17_std
- B_3_mean
- B_23_std
- D_65_last
- B_20_mean
- B_11_mean
- D_140_last
- D_123_max
- D_72_mean
- D_124_max
- B_15_last
- D_49_max
- D_133_max
- S_5_std
- D_62_max
- D_119_last
- D_142_max
- D_43_std
- B_29_std
- B_40_last
- D_122_min
- R_3_first
- D_48_std
- D_61_last
- D_141_mean
- D_48_mean
- R_3_max
- D_70_mean
- S_8_min
- B_26_last
- B_15_max
- S_26_std
- S_25_max
- D_76_max
- B_1_min
- D_47_first
- S_25_min
- B_1_std
- B_13_first
- B_17_min
- R_11_std
- D_43_max
- S_24_mean
- B_13_mean
- B_33_mean
- D_118_mean
- S_22_max
- S_25_last
- D_118_last
- D_131_std
- S_5_mean
- B_22_mean
- D_91_first
- D_132_first
- D_110_max
- S_7_rate_last
- P_2_diff_last
- D_82_mean
- D_128_last
- B_39_first
- D_69_last
- P_2_first
- D_61_first
- D_59_mean
- D_132_last
- D_53_std
- B_21_std
- B_2_rate_last
- R_9_mean
- D_102_std
- B_3_rate_last
- D_74_std
- D_41_first
- D_39_mean
- D_61_max
- D_141_std
- R_3_std
- B_39_min
- B_40_mean
- R_26_first
- B_30_count
- B_37_min
- D_102_max
- B_8_min
- S_3_first
- D_115_max
- D_70_std
- D_54_diff_last
- B_12_mean
- B_4_max
- D_41_diff_last
- B_12_first
- D_41_rate_last
- P_3_first
- D_104_min
- D_82_last
- D_112_mean
- D_60_max
- D_122_max
- D_42_last
- D_63_last
- B_26_mean
- D_39_rate_last
- D_118_max
- R_8_last
- D_106_last
- D_80_last
- D_48_first
- S_27_max
- B_16_std
- S_19_std
- S_23_std
- D_70_last
- D_39_diff_last
- D_110_first
- D_56_mean
- D_119_mean
- B_21_last
- B_37_max
- R_3_rate_last
- D_50_std
- D_41_min
- D_134_mean
- B_8_first
- D_110_min
- S_7_std
- D_71_mean
- R_1_max
- B_12_std
- B_23_max
- D_112_first
- R_5_max
- D_82_max
- B_14_max
- B_17_max
- R_10_last
- R_6_max
- B_39_mean
- D_50_min
- R_1_rate_last
- S_27_mean
- B_25_first
- B_24_std
- D_41_std
- R_5_std
- D_54_min
- R_6_last
- D_48_max
- B_25_mean
- B_7_diff_last
- R_12_std
- D_108_mean
- P_2_rate_last
- D_55_first
- D_63_nunique
- D_54_mean
- D_48_min
- D_84_std
- B_37_first
- B_9_max
- D_86_mean
- D_117_first
- B_19_mean
- S_16_mean
- B_14_mean
- B_16_mean
- R_16_mean
- D_79_std
- D_60_min
- D_121_last
- D_115_last
- B_2_max
- D_128_std
- D_91_last
- B_2_diff_last
- S_15_std
- S_3_diff_last
- D_105_rate_first
- S_24_first
- D_145_mean
- R_6_std
- D_113_last
- B_10_first
- D_134_first
- D_61_mean
- B_21_mean
- D_83_last
- B_12_max
- B_1_max
- D_52_first
- D_105_mean
- D_132_min
- D_142_min
- B_11_min
- D_69_mean
- P_2_diff_first
- B_7_max
- B_16_min
- B_23_min
- D_105_min
- B_1_mean
- B_2_std
- D_144_mean
- S_5_min
- D_142_first
- D_52_max
- D_131_last
- B_26_max
- S_16_last
- D_140_mean
- S_16_max
- D_58_max
- B_18_first
- D_133_last
- B_19_last
- R_16_last
- D_56_std
- S_9_max
- B_12_last
- B_39_max
- B_20_rate_last
- B_13_min
- D_74_last
- B_3_first
- D_124_std
- S_13_mean
- S_23_max
- B_4_rate_first
- D_61_rate_first
- B_6_min
- B_13_max
- S_8_std
- S_11_min
- B_28_mean
- B_39_std
- B_36_std
- D_134_max
- D_70_first
- D_61_min
- S_20_mean
- D_62_std
- B_19_std
- D_60_std
- R_10_std
- D_135_last
- B_28_max
- D_133_std
- D_104_first
- R_14_std
- B_28_last
- D_55_min
- D_134_last
- S_6_mean
- D_59_rate_first
- D_134_min
- D_48_diff_first
- S_11_first
- P_2_rate_first
- S_27_min
- D_53_min
- D_124_mean
- S_22_std
- D_79_last
- D_141_min
- S_19_rate_first
- B_11_std
- P_3_diff_last
- S_12_max
- S_25_mean
- P_3_rate_last
- D_111_std
- B_3_max
- D_91_std
- D_121_std
- B_36_first
- D_110_std
- D_58_min
- B_7_rate_first
- D_136_std
- D_105_diff_first
- B_24_mean
- D_58_first
- D_75_mean
- D_47_diff_first
- B_10_max
- B_5_rate_last
- D_59_last
- D_82_std
- S_23_diff_first
- B_27_min
- B_6_max
- R_12_max
- S_17_last
- B_6_std
- D_45_diff_first
- D_61_rate_last
- B_24_first
- D_62_diff_last
- S_7_min
- S_19_last
- D_144_max
- S_26_min
- D_132_std
- D_137_std
- R_14_max
- D_69_max
- D_73_first
- D_46_std
- D_130_last
- S_25_first
- S_13_last
- D_62_rate_last
- R_14_mean
- D_133_first
- D_45_rate_last
- R_14_first
