path: config/features
name: features.yaml
selected_features:
- P_2_last
- B_11-P_2_mean
- B_7_last
- D_43_last
- D_112_last
- B_4_std
- R_1_last
- B_1_last
- B_9_last
- B_4_last
- D_43_mean
- D_39_last
- B_38_last
- D_45_last
- D_41_last_lag_sub
- D_46_last
- D_39_max
- B_7_diff_last_2
- B_5_mean
- R_2_last
- B_11_last
- D_41_last
- B_5_diff_last_3
- D_39_diff_last
- S_23-P_2_std
- D_42_first
- R_27_last
- B_3_last
- B_3_std
- S_9_min
- D_52_first
- B_5_last
- B_18_last
- D_50_first
- D_61_last
- S_26_mean
- D_50_mean
- S_11_max
- S_3_mean
- D_42_mean
- B_3_last_lag_sub
- D_61_max
- B_9_diff_last
- D_43_min
- D_56_std
- R_6_last_lag_sub
- S_23_diff_last_2
- B_29_min
- D_51_mean
- B_4_diff_last_2
- D_50_max
- S_26_last
- D_39-P_3_std
- S_9_first
- S_3_min
- B_2_last
- D_48_last
- D_47_min
- B_10_min
- R_1_min
- S_15_mean
- D_77_min
- D_61_diff_last
- R_27_min
- D_41_diff_last
- S_3_last
- D_128_mean
- B_14_last_lag_div
- B_23_last
- B_18_std
- B_4_mean
- D_43_std
- D_131-P_2_mean
- D_74_last
- D_55_last_lag_sub
- D_84_max
- B_26_first
- B_11-P_3_mean
- D_69_first
- R_11_mean
- D_46_diff_last_3
- D_69_mean
- S_5_mean
- D_50_last
- S_19_diff_last
- D_48_mean
- B_7_mean
- P_2_last_lag_div
- D_46_min
- S_23-P_3_std
- B_37_last
- B_27_last
- D_42_last_lag_sub
- D_131-P_3_mean
- S_7_diff_last_3
- P_2_last_lag_sub
- R_27_mean
- D_74_mean
- B_11-P_3_std
- B_5_min
- D_132_max
- D_46_last_lag_sub
- B_5_first
- D_69_std
- S_16_max
- S_9_mean
- R_14_mean
- D_48_diff_last_2
- D_112_last_lag_sub
- D_39-P_3_mean
- D_46_first
- R_27_std
- D_62_last
- P_2_diff_last
- B_26_std
- R_1_first
- D_62_mean
- P_3_last
- D_51_first
- B_17_first
- D_70_mean
- D_121_min
- S_11_first
- D_50_std
- D_43_max
- B_2_min
- D_76_min
- S_12_mean
- S_11_mean
- D_121_std
- D_84_std
- S_3_max
- D_60_last_lag_sub
- S_3_first
- B_10_last
- B_36_min
- S_26_min
- D_50_last_lag_div
- S_5_std
- D_45_diff_last_3
- B_9_max
- D_62_diff_last_3
- D_62_max
- B_40_max
- B_8_first
- B_17_mean
- R_6_last
- B_25_last_lag_div
- D_56_last
- B_15_last
- B_14_last
- B_27_first
- D_131-P_2_std
- R_27_last_lag_div
- B_23_std
- D_74_last_lag_div
- B_27_last_lag_div
- S_23-P_3_mean
- B_14_last_lag_sub
- S_5_last_lag_div
- S_22_last_lag_div
- S_23_std
- B_3_last_lag_div
- D_69_last
- R_1_mean
- D_44_last
- D_39_mean
- D_104_std
- S_19_last
- D_132_min
- D_121_last
- D_133_last_lag_sub
- D_58_min
- D_74_std
- D_43_last_lag_sub
- P_2_diff_last_2
- D_102_last_lag_sub
- D_62_diff_last
- B_27_mean
- S_16_std
- D_48_last_lag_div
- S_16-P_2_std
- S_23_max
- R_1_last_lag_sub
- B_2_mean
- D_50_min
- B_26_min
- S_12_first
- S_19_last_lag_div
- D_48_diff_last
- D_56_last_lag_div
- B_17-P_3_std
- S_23_diff_last_3
- P_3_diff_last_2
- D_69_max
- S_11_last
- B_3_min
- D_61_diff_last_3
- B_7_std
- B_24_min
- S_27_mean
- D_144_first
- S_8_max
- S_3_std
- B_21_min
- B_8_last_lag_div
- D_45_diff_last_2
- B_17-P_2_std
- B_3_diff_last
- B_2_std
- B_25_last_lag_sub
- D_61_first
- S_17_std
- S_11_std
- B_12_mean
- B_2_first
- P_2_first
- D_55_last_lag_div
- S_19_max
- D_144_last_lag_sub
- D_45_diff_last
- S_25_mean
- B_24_last
- S_19_min
- D_51_max
- P_2_diff_last_3
- D_48_last_lag_sub
- D_76_last_lag_sub
- S_24_max
- D_133_min
- S_8_last
- D_105_std
- D_71_mean
- D_41_last_lag_div
- D_42_max
- S_7_diff_last
- S_22_last
- B_17_max
- B_36_last_lag_sub
- S_3_diff_last_3
- S_26_diff_last
- D_45_min
- D_69_min
- D_46_mean
- R_3_std
- B_15_min
- S_19_diff_last_3
- D_121_first
- D_133_first
- S_26_last_lag_div
- S_3_diff_last_2
- B_8_min
- S_25_first
- D_45_last_lag_sub
- D_134_last_lag_sub
- D_41_max
- D_46_std
- D_128_last_lag_div
- B_1_last_lag_sub
- D_52_max
- B_6_first
- S_8_last_lag_sub
- D_118_last
- S_8_mean
- B_10_last_lag_div
- B_14-P_3_std
- S_19_std
- D_131_last_lag_div
- S_25_min
- B_11_last_lag_div
- B_4_last_lag_sub
- S_12_max
- B_21_first
- B_15_last_lag_sub
- P_3_last_lag_sub
- S_22_max
- B_3_max
- D_75_last_lag_div
- B_27_min
- D_105_diff_last
- D_49_std
- B_37_std
- S_23_mean
- D_41_diff_last_2
- D_47_mean
- D_56_min
- S_19_diff_last_2
- D_47_max
- B_40_std
- B_13_last_lag_sub
- D_115_max
- B_40_last
- B_8_std
- D_52_min
- D_133_last_lag_div
- B_8_mean
- D_76_last_lag_div
- S_16_min
- B_15_max
- D_41_std
- B_7_last_lag_sub
- D_47_diff_last_3
- D_112_std
- D_112_diff_last_2
- D_48_max
- D_144_last_lag_div
- R_1_std
- B_2_diff_last
- D_47_last_lag_sub
- D_104_last_lag_sub
- S_16_first
- D_59_last_lag_sub
- D_39-P_2_mean
- D_59_diff_last_2
- B_11_last_lag_sub
- D_60_min
- D_39-P_2_std
- R_6_last_lag_div
- B_28_last_lag_div
- D_43_last_lag_div
- S_11_min
- B_5_max
- S_16-P_3_std
- R_12_mean
- S_26_std
- D_128_max
- S_3_last_lag_sub
- D_72_std
- D_102_first
- S_26_diff_last_3
- D_112_diff_last
- S_17_last_lag_div
- B_2_last_lag_div
- B_13_max
- D_119_min
- B_13_last
- D_70_last_lag_div
- D_71_last
- D_48_min
- S_23_min
- B_36_max
- B_4_last_lag_div
- S_24_last
- D_47_last_lag_div
- S_16-P_3_mean
- B_11_min
- B_22_last_lag_div
- D_56_mean
- D_42_last
- D_44_last_lag_div
- B_8_max
- S_8_first
- B_37_mean
- D_59_last_lag_div
- D_118_last_lag_div
- D_124_mean
- D_39_last_lag_sub
- B_14-P_2_mean
- P_3_first
- B_14-P_3_mean
- R_3_mean
- D_53_last_lag_div
- S_11_last_lag_div
- B_24_last_lag_sub
- D_145_last_lag_sub
- D_41_mean
- B_21_max
- D_119_last_lag_sub
- B_2_diff_last_2
- D_53_last_lag_sub
- B_3_diff_last_2
- S_7_last_lag_div
- D_118_std
- D_102_std
- B_21_last_lag_sub
- B_9_last_lag_div
- R_1_last_lag_div
- D_51_min
- D_78_last
- B_40_last_lag_sub
- B_11_first
- S_9_last
- B_10_std
- B_24_max
- D_59_min
- D_62_last_lag_div
- R_16_max
- D_75_diff_last_2
- D_144_mean
- B_14-P_2_std
- B_27_std
- B_12_std
- B_15_first
- S_7_mean
- D_50_last_lag_sub
- B_26_last
- S_26_first
- B_29_last_lag_sub
- D_42_min
- R_5_std
- P_3_mean
- B_36_mean
- B_21_mean
- B_17_last
- R_9_mean
- S_7_first
- S_12_last_lag_div
- D_44_last_lag_sub
- B_6_last_lag_div
- D_77_mean
- S_8_std
- B_6_std
- P_3_max
- D_112_last_lag_div
- D_55_std
- B_24_last_lag_div
- S_15_max
- S_22_mean
- B_8_last_lag_sub
- D_128_min
- B_17_min
- B_36_std
- D_141_std
- D_118_last_lag_sub
- S_16_last
- D_59_first
- D_144_std
- B_13_std
- D_131_last_lag_sub
- S_23_last
- P_2_std
- S_19_first
- D_104_min
- S_27_min
- S_26_max
- R_16_last_lag_div
- B_7_diff_last
- B_28_mean
- D_130_last_lag_sub
- S_7_std
- S_13_std
- S_25_max
- B_9_std
- S_9_last_lag_sub
- S_11_last_lag_sub
- D_43_first
- D_115_std
- D_119_last_lag_div
- B_10_mean
- D_77_last
- D_76_last
- B_9_diff_last_2
- S_17_min
- B_12_last_lag_div
- D_122_first
- R_10_mean
- D_71_min
- D_102_max
- B_5_last_lag_div
- S_24_last_lag_div
- S_23-P_2_mean
- D_48_std
- D_53_max
- D_77_last_lag_div
- S_27_std
- R_3_last_lag_sub
- D_81_std
- D_76_std
- D_61_std
- D_129_mean
- R_10_std
- B_13_last_lag_div
- B_4_max
- D_58_mean
- B_12_last
- D_132_first
- D_51_last_lag_div
- D_118_max
- S_5_first
- B_28_first
- B_6_last
- D_70_std
- S_27_last_lag_sub
- D_102_last_lag_div
- D_47_diff_last
- S_25_last_lag_div
- S_3_last_lag_div
- D_115_mean
- D_44_std
- P_3_diff_last
- B_26_last_lag_div
- D_46_diff_last
- D_130_max
- S_23_first
- B_19_std
- R_12_min
- D_62_std
- S_24_std
- D_104_last_lag_div
- B_25_std
- S_27_first
- D_47_last
- D_62_min
- B_16_last_lag_div
- D_58_std
- D_46_max
- R_1_diff_last
- D_144_max
- R_27_first
- D_56_last_lag_sub
- B_27_last_lag_sub
- R_12_last_lag_div
- R_27_max
- S_3_diff_last
- D_133_std
- D_49_last_lag_div
- P_2_min
- D_102_mean
- D_106_std
- D_41_diff_last_3
- S_12_std
- R_1_diff_last_3
- S_12_last
- D_105_max
- S_18_mean
- D_77_std
- S_17_mean
- D_69_last_lag_sub
- B_40_last_lag_div
- B_14_max
- R_14_max
- D_69_last_lag_div
- B_24_mean
- D_61_min
- D_104_max
- D_115_last_lag_sub
- S_16-P_2_mean
- B_11_std
- D_119_max
- B_16_std
- D_62_diff_last_2
- S_7_last
- D_46_last_lag_div
- D_131_std
- S_22_last_lag_sub
- P_2_max
- D_61_diff_last_2
- B_37_last_lag_sub
- S_9_std
- D_124_max
- D_132_last
- D_64_last
- B_23_last_lag_div
- D_119_mean
- B_25_first
- B_6_min
- D_124_last
- S_19_last_lag_sub
- D_56_max
- D_130_min
- R_3_last_lag_div
- D_53_min
- B_23_first
- D_65_last_lag_div
- D_102_min
- B_36_first
- B_27_max
- D_55_first
- B_24_std
- S_15_std
- S_23_diff_last
- S_24_last_lag_sub
- D_117_count
- D_84_last_lag_div
- D_141_first
- D_62_first
- S_19_mean
- B_17-P_2_mean
- B_19_last_lag_div
- R_11_std
- R_3_diff_last_2
- B_18_first
- B_7_diff_last_3
- B_23_max
- S_25_std
- D_77_max
- D_115_last_lag_div
- B_41_last
- S_15_last_lag_div
- D_71_std
- R_27_last_lag_sub
- S_15_first
- B_25_min
- D_61_last_lag_div
- D_47_first
- P_3_min
- B_16_last_lag_sub
- D_80_std
- R_1_max
- D_55_last
- D_134_mean
- B_20_mean
- B_40_mean
- B_1_max
- D_77_first
- D_52_std
- D_125_mean
- D_131_last
- B_26_mean
- S_13_mean
- D_61_last_lag_sub
- B_12_first
- B_18_last_lag_div
- B_9_diff_last_3
- B_15_mean
- D_47_diff_last_2
- S_24_min
- S_9_last_lag_div
- D_39_last_lag_div
- D_144_last
- B_37_first
- B_8_last
- B_28_last
- S_7_last_lag_sub
- D_89_std
- B_10_max
- D_105_last_lag_sub
- D_128_last_lag_sub
- B_13_mean
- B_7_first
- B_36_last
- S_7_max
- D_42_std
- D_123_std
- R_6_first
- B_17-P_3_mean
- S_17_last
- D_58_max
- B_40_first
- D_59_std
- D_104_first
- S_27_last
- B_20_last_lag_div
- B_25_max
- R_6_min
- B_18_max
- D_48_diff_last_3
- B_22_std
- D_71_first
- S_7_min
- S_16_mean
- B_13_first
- D_58_last_lag_div
- D_75_std
- D_51_std
- S_17_last_lag_sub
- B_12_max
- B_21_last
- B_1_first
- S_26_diff_last_2
- D_105_diff_last_2
- S_16_last_lag_sub
- D_132_mean
- B_20_std
- D_106_last_lag_div
- D_39_diff_last_2
- B_12_last_lag_sub
- B_4_first
- S_5_last
- B_36_last_lag_div
- D_121_max
- B_37_last_lag_div
- S_9_max
- P_4_max
- D_102_last
- D_134_last_lag_div
- D_113_mean
- D_121_last_lag_div
- S_16_last_lag_div
- P_4_last_lag_sub
- D_74_last_lag_sub
- D_49_last
- D_124_min
- D_105_min
- B_14_first
- S_12_min
- D_61_mean
- D_49_last_lag_sub
- R_3_last
- D_132_last_lag_div
- B_14_min
- S_5_last_lag_sub
- D_118_min
- D_60_mean
- B_3_mean
- B_2_diff_last_3
- B_37_min
- D_62_last_lag_sub
- D_47_std
- D_131-P_3_std
- B_7_last_lag_div
- B_9_last_lag_sub
- D_52_last_lag_sub
- S_7_diff_last_2
- B_1_min
- S_13_last_lag_sub
- S_17_first
- D_123_first
- R_21_std
- S_5_min
- D_75_last_lag_sub
- S_12_last_lag_sub
- D_83_last
- D_55_min
- B_6_mean
- D_80_mean
- B_4_diff_last_3
- D_59_mean
- S_22_std
- B_17_last_lag_sub
- R_12_std
- D_53_std
- R_10_last_lag_sub
- R_11_last_lag_div
- S_27_last_lag_div
- D_63_first
- R_26_last_lag_div
- D_133_last
- S_13_last
- B_16_mean
- R_16_mean
- B_14_mean
- D_133_max
- B_4_min
- P_4_first
- D_39_first
- B_18_mean
- B_28_min
- R_1_diff_last_2
- B_5_diff_last
- D_46_diff_last_2
- S_25_last_lag_sub
- R_7_std
- S_26_last_lag_sub
- D_78_last_lag_div
- B_15_last_lag_div
- B_17_std
- D_115_first
- D_60_max
- B_20_diff_last_3
- D_105_diff_last_3
- D_60_first
- B_37_max
- B_17_last_lag_div
- D_80_last_lag_div
- S_27_max
- D_42_last_lag_div
- D_140_mean
- D_136_std
- D_60_last
- D_115_last
- D_79_std
- D_59_diff_last_3
- S_6_mean
- D_112_diff_last_3
- S_23_last_lag_div
- D_75_last
- D_113_first
- D_48_first
- D_83_std
- D_49_mean
- D_71_last_lag_sub
- B_23_min
- D_52_mean
- D_119_first
- B_2_last_lag_sub
- B_32_std
- D_119_std
- D_81_last_lag_div
- D_39_diff_last_3
- B_33_std
- S_15_last_lag_sub
- S_24_first
- B_26_max
- D_117_last
- B_15_std
- R_6_max
- S_15_last
- D_123_last_lag_div
- R_20_mean
- B_40_min
- S_17_max
- B_24_first
- P_4_last
- D_44_mean
- B_1_last_lag_div
- S_6_std
- D_103_std
- D_58_last_lag_sub
- D_78_std
- B_12_min
- B_28_last_lag_sub
- D_75_mean
- D_134_std
- D_80_last_lag_sub
- B_5_std
- B_14_std
- D_115_min
- B_25_mean
- D_80_last
- R_15_last_lag_div
- D_56_first
- B_5_diff_last_2
- D_121_last_lag_sub
- D_65_std
- B_39_min
- B_2_max
- R_10_last_lag_div
- D_123_mean
- B_9_min
- B_11_mean
- D_58_first
- D_121_mean
- D_60_std
- D_141_max
- D_105_mean
- D_70_last
- D_141_last
- D_84_mean
- D_72_mean
- D_122_mean
- D_122_std
- D_107_std
- R_3_first
- B_20_last_lag_sub
- D_52_last
- B_23_mean
- S_23_last_lag_sub
