path: config/features
name: features.yaml
selected_features:
- P_2_last
- B_1_last
- D_39_last
- B_3_std
- B_2_last
- S_3_mean
- R_1_last
- B_4_last
- B_4_std
- R_1_mean
- S_3_last
- B_9_last
- B_5_last
- B_7_last
- B_3_last
- D_41_last
- D_43_last
- D_112_last
- D_62_mean
- D_48_last
- D_44_last
- D_51_mean
- R_2_last
- B_18_last
- D_48_diff_last
- D_49_last
- D_51_last
- D_43_mean
- S_23_last
- D_64_last
- D_42_min
- D_50_max
- S_26_max
- D_66_last
- B_11_last
- D_46_last
- S_11_mean
- D_59_max
- D_39_max
- D_112_std
- D_45_max
- B_4_diff_last
- B_5_min
- B_29_min
- S_15_mean
- D_42_first
- D_77_max
- D_46_mean
- R_27_min
- P_2_mean
- B_9_diff_last
- D_42_mean
- B_7_mean
- D_51_min
- S_9_mean
- S_15_max
- B_4_diff_last_2
- B_2_mean
- D_50_last
- P_3_std
- S_26_mean
- B_10_last
- D_45_mean
- D_50_mean
- R_3_mean
- S_12_std
- D_39_std
- S_11_max
- D_62_min
- D_76_last
- D_123_first
- D_120_last
- B_18_mean
- S_24_last
- B_17_first
- B_18_min
- B_9_diff_last_2
- D_49_std
- R_3_last
- B_22_last
- D_60_last
- R_11_last
- B_29_first
- D_55_std
- B_7_std
- S_9_min
- D_59_std
- D_65_mean
- D_118_first
- D_48_diff_last_2
- B_14_last
- B_29_last
- R_5_last
- D_53_last
- D_129_last
- D_44_max
- D_46_first
- B_2_min
- B_17_last
- B_23_last
- B_29_max
- D_51_max
- D_47_last
- D_43_first
- P_2_min
- D_52_last
- D_47_max
- D_62_last
- D_44_std
- S_5_last
- D_42_max
- D_46_min
- D_122_mean
- P_3_max
- S_12_mean
- D_54_last
- D_47_mean
- D_56_last
- S_8_last
- R_4_last
- D_129_mean
- R_27_last
- P_3_last
- R_7_last
- B_21_max
- D_119_min
- S_9_last
- S_25_std
- D_45_first
- R_3_max
- D_77_mean
- P_3_mean
- S_26_last
- D_121_min
- R_11_mean
- B_40_max
- D_48_diff_last_3
- P_2_max
- D_144_std
- D_65_max
- D_121_mean
- D_121_first
- D_41_mean
- B_17_mean
- S_7_mean
- B_3_diff_last
- S_5_std
- D_117_last
- D_45_last
- D_91_min
- D_71_last
- S_12_min
- D_46_diff_last
- S_3_min
- P_2_std
- B_1_std
- D_119_first
- D_52_mean
- B_8_mean
- D_132_first
- B_9_diff_last_3
- D_50_std
- S_22_std
- B_40_std
- S_7_last
- D_56_min
- D_114_last
- D_65_std
- B_37_std
- S_23_std
- D_63_last
- B_10_std
- D_124_last
- D_132_max
- S_8_mean
- D_142_std
- B_40_last
- D_102_first
- S_8_max
- D_121_max
- D_132_mean
- B_28_min
- D_56_first
- D_128_max
- D_75_std
- S_24_max
- D_105_max
- D_41_std
- B_29_mean
- S_9_first
- D_124_max
- R_26_last
- D_56_mean
- S_3_max
- S_7_min
- S_7_diff_last
- D_61_max
- R_27_first
- B_11_std
- R_12_last
- D_52_min
- D_112_first
- D_131_std
- S_22_last
- B_15_mean
- S_24_std
- B_13_min
- D_53_std
- D_70_mean
- R_1_max
- B_5_max
- B_7_diff_last
- D_41_diff_last_lag_div
- B_14_max
- S_9_std
- D_118_mean
- D_61_diff_last
- B_33_last
- D_128_last
- D_43_min
- B_6_min
- S_24_min
- B_20_last
- B_24_last
- S_5_mean
- R_8_std
- P_3_first
- S_5_max
- B_7_min
- S_25_last
- B_12_first
- D_123_max
- B_26_max
- B_25_last
- S_25_max
- D_118_last
- P_3_min
- D_140_last
- D_110_max
- B_6_last
- B_14_std
- D_65_last
- D_141_mean
- D_118_min
- D_122_last
- D_77_last
- B_37_last
- B_22_mean
- B_7_diff_last_3
- D_77_min
- D_43_max
- D_43_std
- D_42_last
- S_6_mean
- D_56_max
- B_12_min
- R_9_first
- S_24_mean
- S_23_diff_last_3
- D_102_max
- B_25_min
- D_59_last
- B_14_mean
- S_26_std
- B_21_std
- B_18_max
- S_9_max
- R_1_diff_last
- B_18_std
- B_15_last
- B_4_diff_last_3
- D_41_diff_last
- B_6_max
- D_50_first
- D_60_max
- D_105_first
- D_41_diff_last_2
- S_22_first
- D_133_max
- B_37_min
- D_46_max
- D_127_mean
- B_3_diff_last_3
- S_12_max
- D_82_last
- S_11_first
- S_16_mean
- D_44_mean
- D_48_min
- S_16_max
- P_2_diff_last
- D_61_first
- R_16_mean
- D_47_first
- D_74_std
- B_29_std
- D_112_mean
- D_48_std
- D_45_min
- D_48_first
- R_1_diff_last_2
- S_15_last
- D_63_nunique
- D_61_std
- B_10_mean
- D_60_min
- B_33_std
- B_12_max
- B_39_first
- D_141_std
- D_47_min
- R_27_std
- D_61_last
- D_71_min
- B_1_min
- S_5_min
- D_75_last
- R_8_last
- D_123_std
- S_26_first
- B_14_min
- B_28_first
- B_13_first
- S_25_mean
- D_106_last
- R_5_std
- D_118_max
- B_16_first
- B_17_min
- B_26_std
- D_119_last
- B_3_max
- D_41_first
- R_12_min
- B_11_min
- B_2_std
- D_122_max
- D_76_max
- S_27_max
- B_21_mean
- D_39_diff_last
- D_48_max
- B_19_std
- D_121_last
- B_18_first
- B_9_diff_last_lag_div
- B_16_std
- R_1_std
- S_22_mean
- S_11_last
- B_7_diff_last_2
- B_5_mean
- B_2_diff_last
- R_10_std
- B_3_mean
- B_28_max
- B_13_mean
- B_27_std
- R_12_std
- D_91_last
- D_104_last
- D_141_max
- S_8_min
- D_54_min
- B_21_last
- R_9_mean
- B_33_mean
- R_16_std
- D_62_first
- B_12_std
- R_26_mean
- S_7_diff_first
- D_128_mean
- B_20_mean
- S_16_std
- B_16_min
- D_142_max
- D_39_diff_last_lag_div
- D_128_min
- S_26_diff_first
- R_14_std
- B_38_last
- D_144_max
- D_61_min
- B_23_std
- S_23_min
- B_19_first
- D_48_mean
- B_17_max
- R_11_std
- D_61_mean
- D_104_std
- D_70_max
- S_23_diff_last
- D_60_mean
- D_115_last
- S_6_std
- P_2_first
- D_75_max
- B_36_mean
- B_4_max
- R_3_diff_last_lag_div
- S_25_min
- D_111_max
- B_39_std
- D_70_min
- B_6_mean
- S_23_diff_last_2
- D_69_last
- D_46_std
- D_134_min
- R_16_last
- B_9_std
- B_4_mean
- D_52_first
- D_138_max
- S_5_first
- D_48_diff_first
- S_7_diff_last_lag_sub
- D_69_mean
- B_8_std
- B_21_first
- B_5_std
- R_11_max
- B_25_max
- D_70_last
- S_20_std
- D_58_max
- B_11_mean
- B_16_last
- D_110_mean
- B_1_mean
- D_48_diff_last_lag_sub
- S_23_max
- B_3_diff_last_2
- B_16_mean
- R_14_max
- B_9_min
- B_28_mean
- B_15_std
- D_61_diff_last_3
- D_133_mean
- D_134_mean
- D_77_first
- D_74_last
- B_24_mean
- D_134_first
- S_20_mean
- B_40_min
- D_72_last
- D_83_mean
- D_111_mean
- B_36_std
- D_59_diff_first
- R_6_mean
- B_26_last
- D_115_first
- D_53_mean
- D_49_max
- D_110_last
- S_3_first
- D_112_diff_last
- B_13_max
- D_110_min
- D_54_diff_last
- B_39_mean
- S_8_std
- D_78_mean
- R_12_mean
- B_39_last
- D_142_mean
- D_124_mean
- B_23_min
- D_111_last
- D_58_last
- S_27_mean
- D_110_std
- D_140_mean
- D_71_mean
- B_24_max
- S_19_diff_last_lag_div
- R_27_mean
- R_7_mean
- S_23_diff_last_lag_div
- D_111_std
- D_124_diff_first
- D_69_std
- D_110_first
- D_54_diff_last_lag_sub
- S_12_last
- D_69_min
- D_86_mean
- S_7_first
- S_27_first
- D_62_diff_last
- B_19_last
- S_7_std
- B_5_diff_last_2
- B_3_diff_last_lag_sub
- D_54_diff_last_3
- D_112_diff_last_2
- D_61_diff_last_2
- D_54_mean
- S_23_first
- B_2_diff_last_lag_sub
- P_3_diff_last_lag_div
- D_107_min
- B_12_mean
- S_16_min
- D_41_min
- D_105_diff_last
- B_5_diff_last_lag_div
- D_84_std
- D_131_max
- B_5_first
- B_26_first
- D_102_min
- P_3_diff_last_lag_sub
- S_19_min
- S_7_diff_last_3
- S_3_diff_last_2
- D_47_std
- D_134_last
- B_41_std
- D_69_first
- D_105_std
- B_2_diff_first
- D_54_first
- S_23_diff_first
- D_44_first
- S_19_mean
- D_73_mean
- B_20_diff_last
- B_7_diff_last_lag_div
- S_19_diff_last_2
- D_119_std
- D_102_mean
- D_83_last
- R_3_diff_first
- S_22_max
- D_141_min
- B_41_first
- P_4_last
- D_102_last
- D_84_mean
- D_80_last
- D_83_std
- R_13_diff_last_3
- D_75_diff_first
