path: config/features
name: features.yaml
selected_features:
- B_11-P_2_last
- P_2_last
- B_4_last
- D_39_last
- D_131-P_2_last
- S_3_mean
- R_1_last
- B_5_last
- B_3_last
- B_4_std
- P_2_mean
- S_23-P_2_last
- D_62_mean
- D_44_last
- B_7_last
- D_41_last
- S_3_last
- B_1_last
- B_29_mean
- D_46_last
- B_18_last
- P_2_min
- D_42_min
- B_3_std
- D_39-P_2_last
- S_26_max
- D_50_max
- B_9_last
- B_2_mean
- D_43_mean
- D_112_std
- B_2_last
- D_112_last
- S_15_mean
- R_2_last
- D_64_last
- D_43_last
- S_16-P_2_last
- D_42_mean
- D_62_min
- B_3_max
- D_51_min
- D_50_last_2
- D_39_max
- D_51_mean
- D_59_max
- B_11-P_2_mean
- D_66_last
- R_3_mean
- R_1_max
- D_48_last
- D_45_max
- D_49_last
- B_10_last
- B_2_min
- D_42_max
- R_3_last
- S_9_mean
- D_45_mean
- R_27_min
- B_7_mean
- S_24_last
- D_47_last_3
- R_5_last
- S_11_mean
- B_2_last_2
- D_52_last
- S_12_std
- D_121_min
- D_56_last_2
- B_17-P_2_last
- S_3_min
- S_11_max
- B_11_last
- D_118_min
- B_14-P_2_last
- D_51_last
- D_120_last
- D_59_std
- R_11_last
- D_49_std
- S_5_last
- D_46_mean
- D_50_last_3
- D_47_mean
- D_50_last
- S_8_max
- S_8_mean
- D_76_last
- B_23_last
- R_1_mean
- S_9_last
- B_14_last
- B_11-P_2_last_2
- B_14-P_2_std
- P_2_last_2
- B_18_min
- R_4_last
- B_11-P_2_last_3
- S_12_mean
- R_11_mean
- D_47_max
- B_5_min
- S_7_last
- D_77_mean
- P_3_max
- D_45_last_2
- S_26_mean
- B_14-P_2_mean
- B_29_last_3
- D_65_mean
- S_9_min
- R_7_last
- D_44_std
- D_66_last_3
- B_7_std
- D_123_max
- D_82_last
- D_71_last
- D_46_min
- D_39_std
- B_17-P_2_mean
- D_129_mean
- B_40_max
- D_47_last_2
- D_65_std
- B_21_max
- D_77_last
- D_77_last_3
- B_29_last_2
- B_10_last_2
- D_45_last
- D_54_last
- B_5_last_3
- S_25_std
- S_23_last
- B_40_std
- D_56_max
- D_105_max
- R_27_last
- D_91_min
- B_17-P_3_last
- D_56_mean
- S_7_mean
- S_16-P_2_std
- S_22_last
- B_11xP_2_last
- D_60_last
- D_114_last_2
- D_102_max
- S_16-P_3_mean
- D_45_last_3
- D_62_last
- S_5_std
- B_17_last
- B_5_last_2
- D_65_max
- S_26_std
- B_5_max
- S_3_max
- D_119_min
- S_5_max
- B_22_last
- D_121_mean
- D_121_max
- B_20_last
- D_117_last
- D_43_last_2
- D_65_last
- R_3_max
- D_124_max
- D_51_last_3
- B_17xP_2_last
- D_56_last_3
- D_117_last_2
- D_122_mean
- B_40_last
- B_18_last_2
- D_50_mean
- S_13_mean
- B_18_mean
- D_52_min
- D_144_std
- D_124_last
- D_48_std
- D_60_last_2
- D_118_mean
- B_37_last
- D_56_last
- D_39xP_2_std
- D_123_mean
- D_133_max
- S_8_last
- D_53_last
- S_12_min
- D_112_last_2
- R_27_last_3
- B_38_last
- B_14xP_3_mean
- S_26_last
- B_24_last
- S_27_max
- D_39xP_2_last
- D_59_last
- D_142_max
- D_142_std
- B_2_last_3
- D_62_max
- D_39xP_2_last_2
- S_13_max
- D_61_mean
- S_23_std
- R_6_max
- D_122_last
- P_3_last
- D_47_last
- P_3_mean
- B_28_min
- D_62_last_2
- R_10_mean
- D_80_last_2
- D_77_last_2
- D_55_std
- D_44_mean
- D_56_min
- B_28_mean
- B_29_max
- D_46_max
- S_22_mean
- D_43_std
- B_18_std
- D_112_mean
- S_15_max
- B_11_max
- D_41_max
- B_6_last
- D_115_mean
- D_70_mean
- B_37_max
- B_14-P_2_last_2
- R_9_mean
- B_13_min
- D_63_last
- D_82_mean
- D_39_last_3
- R_16_mean
- S_24_max
- D_45_min
- B_14-P_3_std
- R_26_mean
- D_140_last
- S_24_std
- P_4_mean
- S_3_last_3
- P_3_min
- S_15_last
- D_131-P_3_mean
- B_10_min
- B_13_mean
- D_131-P_2_mean
- D_129_last
- R_10_last
- B_14xP_3_last
- S_12_max
- D_76_max
- D_62_last_3
- D_76_mean
- D_141_mean
- S_12_last_2
- B_9_mean
- B_30_count
- D_142_min
- B_1_max
- B_26_last
- B_17-P_2_std
- B_9_last_3
- B_3_last_2
- D_121_last_3
- D_63_nunique
- D_119_mean
- D_39-P_2_mean
- B_10_last_3
- S_23-P_3_last
- D_70_std
- D_121_last
- S_6_mean
- S_23-P_2_std
- S_9_max
- D_114_last
- B_15_max
- R_27_last_2
- D_127_mean
- B_14xP_3_last_3
- D_75_std
- S_22_min
- S_23xP_3_last
- B_2_std
- R_8_std
- S_16-P_3_std
- D_91_last
- P_2_last_3
- D_115_last_2
- B_40_last_2
- R_26_last
- D_66_last_2
- B_10_max
- B_7_max
- D_52_last_2
- R_27_mean
- B_16_last_2
- S_7_last_2
- B_21_mean
- D_52_last_3
- S_11_last
- D_44_max
- B_14_std
- S_25_max
- B_17_mean
- D_72_mean
- R_6_last
- B_17-P_3_std
- S_11_last_3
- D_128_mean
- D_65_last_2
- D_118_max
- P_2_max
- D_134_min
- B_13_max
- D_133_last
- S_16-P_2_last_2
- B_17_min
- D_122_last_2
- D_55_min
- D_119_last_2
- S_5_mean
- D_110_max
- R_1_last_2
- D_42_last
- B_16_std
- B_19_max
- B_11-P_3_last
- D_133_last_2
- B_16_mean
- B_21_std
- D_129_last_2
- D_39-P_3_std
- R_26_max
- D_118_last
- D_72_std
- R_8_last
- D_74_std
- S_16-P_3_last_3
- D_128_max
- D_39-P_3_last_2
- D_39-P_2_std
- D_128_last_2
- B_17xP_2_std
- R_12_last
- D_39-P_2_last_2
- B_39_min
- D_61_max
- S_22_std
- S_16-P_2_last_3
- D_131xP_2_last_3
- S_15_std
- R_1_std
- D_131-P_2_last_3
- S_23xP_2_last_2
- B_5_mean
- D_96_std
- D_142_last
- D_91_mean
- B_16_max
- R_16_last
- B_20_mean
- D_58_std
- B_15_last
- D_83_std
- D_70_min
- R_10_std
- D_123_std
- B_17_std
- D_119_last_3
- D_113_max
- B_18_last_3
- D_64_last_2
- B_22_mean
- S_15_min
- S_23_mean
- B_17-P_3_last_3
- B_11xP_3_last_3
- B_37_mean
- D_124_min
- D_140_mean
- B_16_last
- D_46_last_2
- D_131xP_2_mean
- S_26_last_3
- D_142_last_3
- D_43_max
- B_15_min
- D_78_last
- D_43_last_3
- D_54_mean
- S_26_last_2
- D_41_mean
- D_60_min
- B_12_max
- D_43_min
- D_39xP_2_last_3
- B_11_mean
- R_12_last_2
- S_11_last_2
- B_41_last_2
- D_42_std
- B_9_max
- B_14_min
- S_16-P_3_last_2
- D_91_last_2
- S_17_last_3
- D_132_max
- D_58_min
- B_14xP_2_last_3
- B_11xP_2_last_3
- D_58_mean
- D_84_std
- D_106_std
- D_55_mean
- B_23_max
- B_39_mean
- B_14-P_3_last
- B_21_last
- D_118_last_2
- D_60_max
- B_39_last_2
- B_26_std
- B_14xP_2_last
- B_14_last_2
- D_49_last_2
- B_24_max
- D_39_last_2
- S_23-P_3_std
- B_16_min
- S_8_last_3
- R_12_std
- D_71_min
- S_24_mean
- R_12_last_3
- D_139_mean
- D_70_max
- D_48_last_3
- B_10_std
- B_37_min
- R_27_max
- D_142_mean
- B_40_mean
- S_23-P_2_last_2
- D_56_std
- B_36_std
- B_12_mean
- D_39xP_2_mean
- D_39-P_2_last_3
- B_17xP_3_last_2
- B_4_max
- B_20_last_2
- S_16-P_2_mean
- S_23-P_2_mean
- B_39_max
- B_6_mean
- S_12_last
- D_69_mean
- S_24_last_2
- B_15_std
- B_14_max
- S_7_max
- D_41_std
- S_7_min
- D_69_min
- S_22_last_3
- D_121_last_2
- R_5_std
- D_75_last_3
- B_24_mean
- B_12_min
- D_82_std
- S_23-P_3_last_2
- D_134_mean
- D_111_mean
- B_12_std
- S_13_std
- D_49_max
- D_41_last_2
- R_3_last_2
- D_75_max
- D_133_std
- S_16xP_2_std
- R_14_max
- D_48_max
- B_31_last
- D_105_mean
- R_14_std
- B_11-P_3_mean
- D_79_last
- R_3_std
- D_61_last_2
- B_17xP_2_mean
- D_110_mean
- D_131-P_2_last_2
- D_50_min
- B_39_last_3
- D_131xP_2_std
- D_39-P_3_mean
- B_15_last_2
- D_70_last
- D_111_last
- D_53_std
- B_14xP_3_std
- D_80_last
- D_144_max
- D_104_min
- R_15_last
- D_59_mean
- B_14xP_2_std
- S_3_last_2
- D_110_last
- B_7_last_2
- B_6_last_3
- D_92_std
- B_23_last_2
- D_39xP_3_std
- S_25_last
- D_58_max
- B_11_last_3
- D_86_mean
- R_7_mean
- D_70_last_2
- S_23xP_2_last
- D_60_last_3
- S_16xP_2_last_3
- B_28_last_3
- D_72_max
- D_49_last_3
- B_11-P_3_std
- D_105_min
- D_111_std
- S_25_mean
- D_80_std
- D_83_last
- B_4_last_2
- D_53_min
- S_23xP_2_std
- S_3_std
- D_69_std
- B_25_max
- B_26_max
- B_3_mean
- D_48_min
- D_39_mean
- D_111_last_2
- D_131-P_3_last
- D_69_max
- B_11-P_2_std
- D_80_mean
- D_47_min
- B_14-P_2_last_3
- B_6_max
- D_75_mean
- D_39-P_3_last_3
- B_14xP_2_mean
- B_17xP_3_mean
- S_23_max
- D_73_last_2
- S_23xP_3_mean
- D_69_last
- R_3_last_3
- D_49_mean
- B_32_mean
- B_6_last_2
- D_131-P_3_last_3
- D_145_last_2
- S_17_std
- D_52_mean
- S_16-P_3_last
- D_105_std
- B_17xP_2_last_2
- S_15_last_3
- B_19_mean
- S_23xP_2_last_3
- B_40_min
- D_108_std
- D_122_max
- D_73_last_3
- D_62_std
- D_106_last
- D_48_mean
- D_88_std
- B_6_min
- D_107_min
- B_11_min
- D_142_last_2
- D_39-P_3_last
- D_58_last
- D_113_std
- D_74_mean
- R_6_last_2
- R_7_last_3
- P_3_std
- D_105_last_3
- S_12_last_3
- D_131-P_3_std
- B_22_std
- S_22_max
- D_104_mean