path: config/features
name: features.yaml
selected_features:
- B_11-P_2_last
- D_131-P_2_last
- B_3_std
- B_4_last
- R_1_last
- S_3_mean
- D_39-P_2_last
- B_5_last
- B_3_last
- S_3_last
- B_4_std
- D_62_mean
- D_44_last
- S_23-P_2_last
- D_43_mean
- D_39_last
- D_41_last
- B_9_last
- D_112_std
- D_112_last
- D_42_min
- B_2_mean
- S_16-P_2_last
- D_46_last
- D_43_last
- D_50_max
- B_7_last
- R_2_last
- S_26_max
- D_51_min
- D_59_max
- B_1_last
- D_64_last
- D_45_max
- B_18_min
- S_11_mean
- D_66_last
- D_48_last
- B_2_last
- D_42_mean
- B_18_last
- D_51_mean
- D_46_mean
- B_17-P_2_last
- D_131-P_2_mean
- S_9_mean
- B_29_last
- R_3_last
- D_42_max
- S_15_mean
- S_26_mean
- D_39_max
- R_1_mean
- S_12_std
- B_11-P_2_mean
- D_39xP_3_last
- S_9_min
- R_27_min
- D_47_mean
- R_3_mean
- D_49_last
- D_50_last
- B_5_min
- B_7_mean
- B_11_last
- D_50_mean
- D_45_mean
- D_62_min
- B_10_last
- B_29_min
- D_76_last
- D_51_last
- D_121_min
- D_118_min
- S_5_last
- B_7_std
- B_14-P_2_last
- D_123_max
- D_47_max
- D_120_last
- S_24_last
- D_49_std
- R_11_last
- R_5_last
- D_59_std
- B_40_std
- D_56_last
- R_1_std
- R_4_last
- R_7_last
- D_114_last
- D_39-P_3_std
- S_11_max
- D_129_mean
- S_3_min
- D_54_last
- B_22_last
- B_8_min
- S_15_max
- B_14-P_2_std
- S_12_mean
- S_23-P_2_mean
- D_52_min
- D_56_min
- S_8_mean
- D_91_min
- S_16-P_2_std
- D_47_last
- B_29_max
- B_11xP_2_last
- R_11_mean
- S_9_last
- D_52_last
- D_46_min
- S_16-P_3_mean
- S_8_last
- B_17xP_2_last
- S_13_mean
- D_45_last
- D_121_max
- S_3_max
- P_3_max
- D_39_std
- B_40_last
- D_65_max
- S_16-P_3_std
- D_117_last
- S_23_std
- D_44_std
- B_40_max
- D_119_min
- B_5_mean
- D_129_last
- B_15_mean
- D_65_last
- B_20_last
- D_75_std
- D_52_mean
- D_39-P_3_last
- D_123_mean
- B_18_mean
- D_71_last
- B_23_last
- D_124_last
- S_8_max
- B_2_std
- R_27_last
- D_60_last
- D_39xP_2_std
- D_102_max
- D_105_max
- S_26_last
- B_17-P_2_mean
- P_2_min
- D_44_mean
- B_14-P_2_mean
- B_5_max
- D_121_mean
- D_77_mean
- D_122_mean
- B_6_min
- D_144_std
- D_131-P_3_mean
- B_21_max
- D_65_mean
- B_17_last
- S_7_last
- D_65_std
- P_2_last
- B_4_max
- D_82_mean
- S_9_std
- D_133_max
- S_5_std
- S_12_min
- S_7_mean
- R_26_last
- D_121_last
- D_142_std
- D_128_mean
- S_23xP_2_last
- S_25_std
- B_13_min
- B_14-P_3_std
- D_82_last
- D_53_last
- D_76_mean
- D_44_max
- S_16-P_2_mean
- S_24_min
- R_12_last
- S_23-P_3_std
- D_62_last
- B_37_last
- B_28_min
- S_22_std
- B_2_min
- S_23-P_3_last
- D_56_mean
- B_17_mean
- S_22_last
- D_61_mean
- D_140_last
- S_5_mean
- B_29_mean
- P_3_last
- D_118_mean
- B_6_last
- R_3_max
- R_27_max
- B_13_mean
- S_11_last
- B_8_mean
- D_39-P_3_mean
- D_39xP_2_last
- S_26_std
- D_52_max
- D_124_max
- D_43_std
- B_5_std
- S_23_last
- B_24_last
- B_20_max
- B_29_std
- B_26_last
- B_25_min
- B_17-P_3_last
- B_17-P_2_std
- D_118_last
- S_7_min
- D_70_mean
- B_15_max
- S_23xP_3_std
- B_14xP_3_last
- D_132_mean
- D_55_std
- D_48_std
- D_39-P_2_std
- B_3_mean
- D_50_min
- B_9_mean
- B_11xP_3_last
- D_43_min
- D_77_last
- D_112_mean
- B_12_max
- D_128_min
- S_15_min
- B_10_std
- B_15_last
- S_13_max
- B_1_max
- D_41_std
- S_16xP_2_std
- D_110_max
- B_37_max
- D_76_max
- D_45_min
- B_17-P_3_mean
- D_46_max
- D_128_max
- S_5_max
- D_141_max
- R_1_max
- B_11-P_2_std
- D_53_std
- B_14-P_3_last
- D_113_max
- B_13_max
- R_8_last
- D_133_last
- D_92_mean
- D_122_max
- R_27_mean
- D_48_max
- R_8_std
- D_71_mean
- D_54_min
- D_49_max
- D_61_min
- B_11xP_2_std
- S_16xP_2_mean
- D_132_min
- B_12_mean
- B_12_last
- B_10_mean
- D_119_mean
- D_77_max
- B_14_mean
- R_10_last
- S_22_min
- S_24_mean
- D_141_mean
- R_16_mean
- S_12_last
- D_134_min
- S_23xP_3_last
- B_37_mean
- D_70_max
- D_74_std
- S_24_std
- R_11_std
- D_63_last
- S_16xP_2_last
- B_28_mean
- D_59_last
- B_39_min
- D_43_max
- B_26_mean
- B_11-P_3_mean
- D_60_mean
- D_112_min
- B_20_mean
- P_2_max
- D_56_max
- D_61_std
- D_70_std
- R_26_mean
- S_12_max
- D_56_std
- D_78_last
- D_119_max
- D_41_max
- D_141_std
- D_131xP_3_last
- D_70_min
- B_11-P_3_last
- D_132_max
- B_18_std
- B_14xP_3_std
- B_14_last
- B_11xP_3_mean
- B_39_mean
- B_16_mean
- B_25_max
- D_72_std
- B_7_max
- B_17xP_2_mean
- D_79_max
- S_25_last
- B_11_max
- S_9_max
- S_3_std
- D_128_std
- D_42_last
- R_6_std
- P_3_mean
- B_21_last
- D_91_mean
- D_48_mean
- B_14xP_3_mean
- D_128_last
- B_14xP_2_last
- D_142_last
- S_27_max
- D_48_min
- D_41_mean
- D_102_std
- B_16_min
- S_23xP_3_mean
- B_3_max
- S_23-P_2_std
- B_17-P_3_std
- D_55_min
- R_9_mean
- B_22_mean
- B_17xP_2_std
- S_16xP_3_std
- S_23_mean
- D_76_min
- B_37_min
- D_83_mean
- D_53_min
- D_60_max
- D_126_nunique
- B_18_max
- B_21_std
- D_75_max
- B_19_std
- D_74_max
- D_115_std
- D_47_min
- B_14_min
- D_133_mean
- R_15_std
- D_71_max
- D_54_mean
- D_142_max
- B_26_std
- R_26_std
- D_80_last
- D_131-P_3_last
- S_23xP_2_std
- B_25_last
- B_14_max
- D_140_mean
- S_8_std
- D_124_min
- D_107_std
- D_53_max
- P_2_mean
- R_10_mean
- R_15_last
- B_31_last
- B_3_min
- D_131_last
- S_16_mean
- S_16_std
- S_7_max
- B_8_max
- D_71_min
- B_24_max
- R_10_std
- B_24_mean
- B_23_max
- B_14xP_2_std
- D_119_last
- S_20_mean
- B_8_last
- D_122_last
- D_58_last
- B_2_max
- D_72_mean
- D_41_min
- D_124_std
- D_61_last
- S_27_std
- R_5_std
- D_143_mean
- R_15_mean
- B_12_std
- R_14_std
- B_21_min
- D_104_max
- D_110_last
- P_3_std
- B_27_std
- B_17_max
- B_21_mean
- D_134_mean
- P_3_min
- D_39xP_3_mean
- B_17_min
- D_75_mean
- D_62_max
- D_104_mean
- D_104_min
- D_142_min
- B_11-P_3_std
- D_105_mean
- S_16_max
- R_12_std
- D_69_min
- D_53_mean
- D_141_min
- D_102_mean
- B_9_max
- D_82_std
- B_20_std
- S_19_std
- S_24_max
- B_10_min
- R_7_std
- B_24_std
- D_39_mean
- S_17_std
- S_23_min
- R_6_max
- B_36_mean
- S_23_max
- D_105_min
- B_15_min
- B_20_min
- D_132_last
- S_7_std
- B_19_min
- D_123_std
- D_130_mean
- D_111_std
- D_124_mean
- D_104_last
- B_26_min
- B_11_mean
- D_58_max
- B_39_std
- D_131-P_3_std
- S_16-P_3_last
- S_5_min
- D_59_mean
- D_134_max
- D_69_last
- D_130_min
- D_111_mean
- B_7_min
- B_23_min
- S_17_mean
- D_102_min
- B_11xP_2_mean
- D_42_std
- D_131xP_2_last
- S_27_last
- B_19_mean
- B_6_mean
- B_26_max
- B_1_min
- B_40_mean
- D_131_min
- B_36_max
- B_28_std
- D_133_std
- D_137_std
- B_28_max
- B_11_min
- D_81_std
- D_39-P_2_mean
- R_16_last
- B_27_min
- B_10_max
- D_115_min
- D_77_min
- S_16_min
- S_15_std
- S_27_min
- B_11_std
- D_83_last
- D_58_std
- D_121_std
