path: config/features
name: features.yaml
selected_features:
- P_2_last
- B_1_last
- P_2_last_round2
- D_39_last
- S_3_mean
- B_3_std
- R_1_mean
- D_62_mean
- S_3_last
- R_1_last_round2
- B_5_last
- B_4_last
- D_43_mean
- B_7_last
- B_2_last
- B_2_last_round2
- D_41_lag_sub
- R_2_last
- D_43_last
- B_18_last_round2
- D_39_max
- D_44_last
- B_4_lag_sub
- B_4_max
- D_51_min
- B_4_std
- S_26_max
- D_51_mean
- B_9_last_round2
- D_50_max
- D_42_first
- R_27_min
- B_9_last
- B_2_mean
- D_42_min
- D_45_first
- D_66_last
- B_4_last_mean_diff
- P_2_mean
- B_11_last
- D_59_max
- D_64_last
- B_3_last_round2
- S_25_std
- B_7_mean
- D_48_diff1
- D_112_last
- S_11_mean
- R_1_last
- S_15_mean
- D_49_last
- D_48_last
- B_3_max
- S_26_mean
- D_41_last_mean_diff
- D_45_mean
- D_46_first
- S_12_std
- S_9_min
- D_50_last
- D_48_last_mean_diff
- D_42_mean
- D_49_last_mean_diff
- D_62_min
- D_39_last_mean_diff
- D_44_last_mean_diff
- D_51_last
- B_3_lag_sub
- D_50_mean
- D_45_max
- S_3_min
- B_3_last
- B_18_min
- R_3_mean
- B_9_diff1
- D_39_std
- D_76_last
- B_29_min
- P_3_std
- D_46_last
- B_18_last
- B_3_last_mean_diff
- B_17_first
- D_123_first
- B_2_min
- D_120_last
- S_23_last
- S_11_max
- D_122_mean
- R_3_last
- D_65_mean
- S_9_mean
- B_29_diff1
- D_65_max
- R_11_last
- D_46_diff1
- B_10_min
- P_2_min
- B_29_last
- D_48_last_round2
- B_29_lag_sub
- D_118_first
- D_43_first
- D_47_mean
- D_59_std
- S_5_diff1
- P_3_max
- B_5_min
- S_24_last
- S_15_max
- R_5_last
- D_129_mean
- D_50_last_mean_diff
- B_40_max
- D_48_lag_sub
- S_24_last_mean_diff
- D_77_max
- P_2_max
- S_8_mean
- B_21_max
- D_112_std
- S_23_last_round2
- S_8_last
- B_22_last
- D_112_lag_sub
- D_56_max
- S_12_mean
- D_121_first
- D_112_min
- S_3_max
- D_118_min
- D_41_last
- B_11_last_round2
- B_1_last_round2
- D_65_std
- D_77_mean
- D_56_first
- D_56_mean
- S_9_first
- B_29_first
- R_4_last
- D_52_min
- D_119_min
- D_49_std
- S_22_last_mean_diff
- D_42_max
- D_46_mean
- D_43_last_round2
- B_17_last
- D_117_last
- D_46_last_mean_diff
- B_7_max
- D_44_std
- B_23_last
- B_6_min
- S_9_last
- B_9_last_mean_diff
- D_54_last
- B_14_last
- P_3_first
- S_24_max
- B_10_last_mean_diff
- B_7_last_round2
- D_39_lag_sub
- S_7_last
- R_27_last
- R_7_last
- B_40_std
- B_7_std
- D_114_last
- D_60_last_round2
- S_5_std
- B_29_last_mean_diff
- D_47_max
- B_15_mean
- D_46_first_round2
- R_5_lag_sub
- D_128_mean
- D_121_min
- D_121_mean
- D_50_diff1
- D_56_last
- S_26_std
- D_44_max
- B_37_diff1
- S_9_last_round2
- B_22_mean
- D_62_last
- D_52_last
- R_11_mean
- D_53_last
- D_124_max
- B_29_max
- B_29_first_round2
- B_23_max
- D_61_diff1
- R_5_last_mean_diff
- S_13_max
- B_25_diff1
- S_7_mean
- P_3_mean
- B_6_last
- D_52_mean
- B_14_last_round2
- B_29_std
- D_56_min
- D_142_std
- P_2_lag_sub
- D_131_std
- B_15_last_mean_diff
- D_144_lag_sub
- B_1_diff1
- P_2_std
- D_82_last
- S_8_max
- B_20_max
- B_10_mean
- D_50_lag_sub
- D_91_min
- B_1_last_mean_diff
- B_24_last_round2
- D_47_last
- D_141_max
- D_39_mean
- R_1_max
- S_9_std
- S_23_std
- B_28_diff1
- D_43_diff1
- B_10_last_round2
- D_60_last
- B_37_last
- D_132_first_round2
- S_26_last
- B_17_mean
- B_29_mean
- R_27_first
- B_1_lag_sub
- D_121_max
- D_132_first
- B_14_std
- D_105_max
- B_4_diff1
- D_70_mean
- R_26_max
- D_105_first
- D_75_std
- D_42_first_round2
- S_5_last
- B_20_mean
- D_102_first
- S_5_max
- R_1_std
- D_48_max
- R_3_max
- D_124_last
- S_24_std
- B_37_last_mean_diff
- D_118_last
- D_47_first_round2
- D_112_last_mean_diff
- D_102_lag_sub
- D_76_max
- B_23_last_round2
- B_23_diff1
- S_12_last_mean_diff
- D_128_max
- D_48_mean
- D_110_max
- D_119_mean
- S_7_last_mean_diff
- B_37_max
- R_16_std
- D_59_last
- B_17_lag_sub
- S_25_max
- S_9_max
- D_121_first_round2
- R_12_last
- B_11_last_mean_diff
- B_5_lag_sub
- D_144_std
- B_5_max
- D_77_min
- D_104_min
- D_47_first
- R_3_first
- R_26_last
- D_77_last
- D_140_last
- D_129_last
- B_20_last
- B_17_std
- D_72_mean
- D_42_last
- B_3_mean
- D_71_last
- D_133_max
- P_3_last_round2
- S_16_mean
- D_74_max
- S_26_last_round2
- B_8_min
- R_7_lag_sub
- D_122_last
- P_2_diff1
- D_119_first
- B_10_last
- S_27_std
- D_62_max
- B_12_max
- D_48_min
- D_56_std
- B_23_std
- D_71_min
- P_2_first
- B_15_last_round2
- B_14_max
- B_19_last
- B_3_diff1
- D_47_min
- D_55_last_mean_diff
- B_21_std
- B_23_lag_sub
- D_74_std
- D_54_min
- S_27_max
- D_45_last_round2
- B_18_mean
- D_45_first_round2
- S_3_first
- D_49_max
- D_55_mean
- D_47_last_round2
- B_11_diff1
- D_63_last
- S_7_diff1
- B_26_diff1
- D_52_diff1
- S_3_last_round2
- P_2_last_mean_diff
- D_43_min
- D_46_std
- R_1_last_mean_diff
- D_75_max
- B_37_min
- D_44_mean
- S_12_min
- D_144_last_mean_diff
- D_41_diff1
- D_78_last_mean_diff
- D_45_last
- R_9_mean
- D_102_std
- D_134_min
- B_13_mean
- B_39_min
- B_39_first
- D_61_std
- S_23_lag_sub
- D_118_first_round2
- R_10_std
- D_132_max
- B_18_std
- P_3_min
- D_129_lag_sub
- D_53_std
- S_3_last_mean_diff
- B_14_last_mean_diff
- S_8_min
- D_112_mean
- S_26_first
- D_49_lag_sub
- D_106_last
- D_53_lag_sub
- B_14_diff1
- D_42_last_round2
- B_37_last_round2
- S_12_diff1
- R_10_last_mean_diff
- D_46_min
- D_43_std
- D_61_first
- D_123_lag_sub
- D_82_mean
- D_127_last
- D_52_lag_sub
- B_28_min
- B_26_lag_sub
- D_102_first_round2
- D_107_lag_sub
- S_7_max
- B_8_mean
- B_5_last_round2
- B_19_max
- D_50_std
- P_3_lag_sub
- D_126_nunique
- S_26_diff1
- D_119_max
- D_123_std
- B_11_mean
- S_23_last_mean_diff
- D_61_min
- R_5_std
- B_2_lag_sub
- R_6_std
- B_28_first
- B_28_last_mean_diff
- D_46_last_round2
- B_2_diff1
- D_41_max
- B_4_mean
- B_12_mean
- B_2_std
- D_132_last_mean_diff
- R_6_max
- P_3_last
- S_5_last_round2
- D_128_diff1
- B_18_last_mean_diff
- D_61_mean
- S_5_mean
- D_118_max
- D_61_last_round2
- B_15_first
- B_25_mean
- D_70_std
- D_43_lag_sub
- B_17_last_mean_diff
- D_71_last_round2
- D_141_std
- S_24_diff1
- D_106_std
- D_91_last
- S_15_last
- S_23_mean
- R_8_std
- R_26_first
- B_33_std
- D_56_lag_sub
- B_37_lag_sub
- B_17_min
- D_132_diff1
- D_141_lag_sub
- D_50_min
- B_39_mean
- B_5_mean
- B_10_std
- S_6_std
- S_24_mean
- B_2_last_mean_diff
- B_6_last_mean_diff
- D_142_last_round2
- D_123_max
- S_27_mean
- R_6_last_round2
- B_6_std
- D_121_last
- B_17_diff1
- D_132_min
- D_71_last_mean_diff
- D_140_mean
- D_62_first
- S_3_diff1
- S_16_std
- D_72_std
- B_17_first_round2
- D_58_max
- D_59_diff1
- D_72_last_mean_diff
- B_21_mean
- D_60_last_mean_diff
- R_8_lag_sub
- D_49_mean
- B_21_last_mean_diff
- R_9_min
- B_13_first
- B_13_max
- R_1_min
- D_92_mean
- B_28_first_round2
- D_77_std
- B_14_lag_sub
- D_53_min
- D_61_last
- S_5_min
- B_9_lag_sub
- D_119_last_round2
- D_60_min
- B_19_mean
- B_19_last_mean_diff
- R_1_lag_sub
- R_7_last_round2
- S_23_min
- D_139_mean
- B_18_diff1
- B_41_std
- B_20_last_mean_diff
- D_133_last
- D_119_last
- D_105_mean
- D_104_std
- B_24_lag_sub
- S_13_last_mean_diff
- S_15_std
- S_25_last_round2
- D_61_max
- D_39_diff1
- B_20_lag_sub
- B_9_mean
- D_41_mean
- B_39_diff1
- D_108_std
- D_76_min
- D_54_mean
- D_60_diff1
- B_16_max
- D_83_mean
- R_16_last_mean_diff
- R_7_diff1
- B_3_first_round2
- B_16_last_mean_diff
- S_7_min
- D_59_mean
- B_26_max
- S_9_last_mean_diff
- P_3_last_mean_diff
- S_5_first
- D_118_lag_sub
- B_24_mean
- B_21_last_round2
- S_15_last_mean_diff
- B_15_last
- B_23_last_mean_diff
- D_65_last
- D_118_last_round2
- B_11_max
- D_123_mean
- B_26_std
- S_25_diff1
- D_130_std
- B_24_max
- D_83_last
- D_110_min
- B_10_max
- S_12_last_round2
- B_4_min
- B_21_lag_sub
- D_102_diff1
- R_15_std
- S_23_max
- D_80_last_mean_diff
- B_36_diff1
- D_82_lag_sub
- B_9_max
- B_14_min
- R_12_min
- R_11_std
- D_134_first
- D_124_mean
- B_23_mean
- R_27_max
- S_7_last_round2
- D_59_lag_sub
- D_53_last_round2
- D_138_last_mean_diff
- B_11_min
- B_28_max
- B_9_min
- S_7_std
- B_39_lag_sub
- B_11_first
- R_11_last_mean_diff
- B_12_last
- R_12_lag_sub
- B_22_last_mean_diff
- D_78_std
- B_10_diff1
- B_7_min
- D_42_last_mean_diff
- S_9_lag_sub
- B_24_last_mean_diff
- B_6_lag_sub
- S_24_min
- S_12_last
- D_106_last_mean_diff
- S_3_std
- S_22_lag_sub
- D_75_last_mean_diff
- S_22_std
- D_111_max
- D_110_lag_sub
- D_110_diff1
- S_25_last
- D_58_last_mean_diff
- SDist_std
- R_27_lag_sub
- S_19_last_mean_diff
- B_40_first
- R_12_diff1
- R_20_std
- B_18_first
- B_28_mean
- D_104_max
- R_3_std
- B_17_max
- B_36_mean
- D_134_mean
- R_24_last_mean_diff
- D_83_lag_sub
- D_55_max
- S_11_lag_sub
- R_12_std
- D_102_min
- S_22_first
- R_15_last_mean_diff
- B_6_max
- D_60_lag_sub
- D_110_last_mean_diff
- D_69_lag_sub
- B_27_last
- D_62_std
- R_16_mean
- D_134_last_mean_diff
- D_124_last_mean_diff
- D_104_lag_sub
- P_4_lag_sub
- D_104_first_round2
- S_25_lag_sub
- B_18_lag_sub
- D_54_max
- D_108_last_mean_diff
- D_45_min
- D_128_lag_sub
- S_26_min
- B_13_last
- B_24_last
- D_69_last_round2
- D_82_last_mean_diff
- S_22_mean
- D_133_std
- D_113_mean
- R_27_std
- D_141_diff1
- D_134_std
- S_17_mean
- S_9_first_round2
- B_25_min
- D_72_diff1
- D_133_first
- D_102_max
- D_121_diff1
- B_40_last
- S_16_first
- R_6_mean
- B_24_diff1
- R_14_lag_sub
- S_17_diff1
- B_1_max
- R_14_max
- R_9_last_mean_diff
- D_56_last_mean_diff
- B_25_lag_sub
- R_22_last_mean_diff
- R_14_last_mean_diff
- D_74_last
- B_13_std
- S_16_last_mean_diff
- D_69_max
- D_58_lag_sub
- D_55_first
- R_14_first
cat_features:
- D_66_last
- D_64_last
- D_120_last
- D_117_last
- D_114_last
- D_63_last
