path: config/features
name: features.yaml
selected_features:
- B_11-P_2_last
- D_131-P_2_last
- S_3_mean
- R_1_last
- D_62_mean
- B_5_last
- D_39_last
- S_23-P_2_last
- D_44_last
- D_41_diff_mean
- B_4_diff_mean
- S_3_last
- B_3_std
- D_43_mean
- B_4_last
- B_3_diff_std
- B_3_last
- S_16-P_2_last
- D_39-P_2_last
- R_2_last
- D_43_last
- D_48_diff_last
- D_51_mean
- B_2_mean
- D_42_mean
- D_39_max
- B_9_last
- D_64_last
- B_4_std
- B_29_min
- B_3_diff_mean
- B_18_last
- D_50_max
- D_46_last
- B_18_min
- D_59_max
- D_66_last
- S_11_mean
- D_51_min
- D_112_last
- B_7_last
- D_50_mean
- S_16-P_2_mean
- D_42_min
- B_2_last
- D_45_max
- S_9_mean
- D_48_diff_mean
- D_45_mean
- S_15_mean
- B_4_max
- B_7_mean
- D_118_min
- B_1_last
- B_17-P_2_last
- D_62_min
- D_48_last
- B_11_last
- B_40_std
- B_9_diff_last
- S_12_std
- B_10_last
- D_52_last
- D_50_last
- B_29_last
- R_1_mean
- D_47_mean
- S_9_min
- B_14-P_2_last
- S_26_max
- S_26_mean
- D_131-P_2_mean
- D_42_max
- R_3_last
- R_1_diff_std
- D_46_mean
- B_40_max
- B_11-P_2_mean
- D_49_last
- D_49_std
- D_120_last
- D_123_max
- B_5_min
- B_9_diff_last_2
- B_4_diff_last_2
- D_76_last
- R_11_mean
- B_22_last
- D_51_last
- S_11_max
- R_5_last
- R_3_mean
- D_47_last
- S_24_last
- S_25_std
- D_112_std
- D_129_last
- R_7_last
- R_11_last
- D_121_min
- S_16-P_2_std
- R_4_last
- S_8_last
- D_77_mean
- S_23-P_2_mean
- D_47_max
- D_129_mean
- D_48_diff_last_2
- D_56_min
- D_39_std
- B_29_max
- P_3_max
- S_8_mean
- R_27_min
- B_4_diff_last
- S_12_mean
- D_59_std
- D_71_last
- S_5_last
- D_44_std
- D_65_max
- D_54_last
- D_60_last
- D_46_diff_last
- D_56_last
- D_117_last
- S_3_min
- B_7_std
- D_39_diff_mean
- S_23-P_3_std
- D_41_last
- B_1_max
- D_48_diff_last_3
- S_9_last
- S_15_max
- B_14-P_3_std
- B_8_min
- D_144_std
- S_8_max
- D_45_last
- D_121_last
- B_9_diff_mean
- S_26_std
- S_26_diff_std
- D_39-P_3_std
- D_91_min
- B_21_max
- D_82_mean
- S_16-P_3_mean
- B_14-P_2_std
- P_2_last
- S_7_last
- R_26_max
- D_46_max
- D_105_max
- D_65_std
- S_23_diff_std
- D_41_mean
- R_27_last
- B_14-P_2_mean
- D_121_mean
- D_112_diff_mean
- S_5_max
- B_17-P_2_mean
- D_44_mean
- B_3_diff_last
- S_12_min
- D_114_last
- D_128_max
- D_141_max
- B_10_min
- D_123_mean
- B_15_mean
- B_6_last
- P_2_diff_mean
- B_5_mean
- D_122_mean
- D_112_min
- D_56_mean
- B_13_mean
- D_45_min
- D_102_max
- B_23_last
- D_121_max
- D_65_mean
- S_13_max
- D_44_max
- S_22_std
- B_17_last
- D_119_min
- R_3_max
- R_12_last
- B_7_diff_last
- S_23-P_2_std
- S_25_max
- B_37_std
- D_112_diff_std
- D_75_diff_std
- B_9_diff_last_3
- D_61_mean
- D_119_max
- D_39-P_3_last
- D_65_last
- P_2_min
- D_75_std
- D_124_min
- D_43_min
- B_14_last
- B_29_mean
- B_26_last
- D_132_max
- D_76_max
- D_52_mean
- B_3_max
- S_13_last
- D_56_max
- P_2_mean
- S_16-P_3_std
- D_70_mean
- D_74_std
- S_7_max
- S_23_std
- S_7_diff_last
- B_6_min
- S_3_max
- R_26_last
- B_7_diff_std
- D_63_last
- B_5_max
- R_27_mean
- D_61_diff_last
- B_17-P_3_std
- B_10_std
- B_17_mean
- S_24_min
- D_82_last
- D_119_mean
- B_22_mean
- D_133_max
- S_5_mean
- B_2_diff_mean
- D_50_min
- R_8_std
- R_6_max
- R_16_mean
- B_21_std
- S_5_std
- D_48_max
- D_43_std
- D_118_last
- R_1_std
- D_76_mean
- B_17-P_3_last
- B_24_last
- S_8_min
- S_9_std
- B_18_mean
- D_132_min
- D_110_max
- B_2_min
- B_11_max
- D_140_last
- D_132_mean
- D_124_max
- B_2_std
- B_40_last
- D_52_max
- D_102_std
- B_23_max
- D_53_last
- S_26_last
- R_9_mean
- B_8_mean
- D_133_last
- D_113_max
- D_48_min
- S_24_max
- B_12_max
- B_20_diff_mean
- D_133_mean
- B_39_min
- D_145_mean
- D_131-P_3_mean
- S_9_max
- D_70_std
- D_134_min
- R_8_last
- D_69_last
- D_46_diff_std
- D_72_mean
- P_2_diff_last
- R_10_std
- B_17-P_3_mean
- S_23_last
- S_7_min
- D_71_mean
- B_11-P_3_mean
- D_62_diff_std
- P_2_max
- S_23_mean
- D_46_min
- D_39-P_3_mean
- D_112_mean
- D_46_diff_last_2
- B_17_std
- B_7_diff_mean
- S_6_std
- D_48_std
- D_125_std
- S_7_diff_mean
- D_60_mean
- B_13_min
- D_61_diff_last_3
- B_4_min
- D_39_diff_last
- B_28_mean
- D_142_std
- S_12_max
- D_107_mean
- B_3_diff_last_2
- D_47_min
- D_59_mean
- D_105_diff_last
- D_142_max
- D_77_last
- S_27_mean
- R_1_max
- B_39_mean
- D_39-P_2_std
- D_79_last
- D_78_last
- B_12_mean
- B_10_max
- D_128_last
- S_16_max
- D_131_last
- B_26_mean
- R_10_last
- S_7_mean
- B_37_max
- D_58_max
- B_11-P_3_last
- D_41_diff_last
- B_17_min
- D_128_mean
- B_21_last
- D_138_std
- D_42_last
- S_25_last
- S_22_max
- S_3_diff_std
- D_79_max
- S_20_mean
- P_3_diff_mean
- D_59_diff_mean
- D_60_min
- D_54_min
- B_15_last
- B_14-P_3_last
- D_61_max
- S_7_diff_last_2
- R_26_mean
- D_70_max
- B_40_min
- D_55_std
- D_61_diff_mean
- D_131-P_3_std
- R_5_std
- B_1_mean
- S_22_min
- S_22_last
- R_27_std
- B_28_last
- S_3_diff_last
- D_96_mean
- D_61_diff_std
- B_25_mean
- D_48_diff_std
- B_4_mean
- D_102_min
- D_82_std
- D_118_max
- D_41_max
- B_37_min
- D_39-P_2_mean
- D_92_std
- B_16_min
- R_14_max
- D_78_mean
- D_119_last
- B_16_std
- B_11-P_2_std
- R_1_diff_last
- S_19_last
- D_58_last
- D_134_mean
- B_37_last
- D_139_mean
- B_40_mean
- D_54_mean
- B_31_last
- B_28_min
- B_9_max
- D_105_min
- B_14_max
- B_12_last
- D_140_mean
- B_29_std
- D_53_mean
- D_53_std
- D_122_min
- D_118_mean
- B_9_diff_std
- S_17_last
- D_124_mean
- S_16_mean
- B_25_last
- D_58_mean
- B_12_std
- B_19_mean
- S_23_max
- B_11_min
- P_3_last
- D_61_last
- D_62_diff_last_3
- B_39_std
- B_11_std
- B_3_min
- B_11_mean
- D_60_std
- B_10_mean
- B_26_std
- P_3_min
- S_19_max
- D_53_min
- D_52_min
- S_3_diff_last_3
- D_61_min
- R_12_min
- S_11_last
- R_15_mean
- D_75_last
- B_24_std
- D_115_max
- R_9_min
- S_12_last
- D_43_max
- B_28_max
- B_24_min
- R_3_diff_std
- B_19_min
- S_3_std
- D_71_std
- B_7_diff_last_3
- D_104_max
- D_59_diff_last
- D_104_std
- D_111_mean
- B_18_std
- S_7_diff_std
- D_111_std
- S_24_mean
- R_4_std
- R_3_min
- S_3_diff_mean
- D_41_diff_std
- B_23_mean
- B_2_diff_last_2
- S_17_min
- S_7_std
- D_63_nunique
- D_83_last
- D_117_count
- D_110_mean
- B_7_max
- D_144_min
- S_26_diff_last_3
- D_49_max
- D_77_std
- B_1_min
- B_2_diff_last
- B_7_diff_last_2
- D_39_diff_std
- B_39_last
- P_3_diff_last
- R_25_mean
- B_4_diff_std
- R_16_last
- S_25_min
- D_69_std
- B_36_min
- R_16_std
- B_36_last
- S_5_min
- B_14_std
- S_19_diff_std
- B_36_std
- D_61_diff_last_2
- P_2_diff_last_3
- D_128_std
- D_105_diff_last_2
- D_62_last
- R_6_mean
- B_13_std
- B_37_mean
- B_6_mean
- D_144_max
- B_8_std
- B_27_std
- D_71_min
- S_23-P_3_last
- S_26_diff_mean
- S_15_last
- S_7_diff_last_3
- R_14_mean
- P_3_diff_last_3
- S_25_mean
- B_9_mean
- D_89_std
- B_2_max
- D_89_mean
- D_59_last
- D_76_min
- R_1_diff_last_3
- D_55_last
- R_14_std
- D_54_max
- D_54_std
- D_112_diff_last
- B_4_diff_last_3
- D_54_diff_last_2
- B_24_mean
- D_112_diff_last_2
- D_83_mean
- P_2_diff_std
- B_3_mean
- D_131_std
- S_23_diff_last_2
- D_41_min
- D_132_std
- R_3_diff_mean
- D_134_last
- S_23-P_3_mean
- D_130_max
- S_16-P_3_last
- D_124_diff_last_3
