path: config/features
name: features.yaml
selected_features:
- P_2_last
- B_1_last
- D_39_last
- B_2_last
- S_3_mean
- B_4_last
- R_1_last
- B_3_std
- B_4_std
- B_7_last
- S_3_last
- B_9_last
- D_41_last
- B_5_last
- B_3_last
- D_62_mean
- R_1_mean
- D_43_mean
- B_18_last
- D_48_last
- D_44_last
- R_2_last
- D_50_last
- D_43_last
- D_48_diff_last
- D_112_std
- D_49_last
- D_42_mean
- D_112_last
- D_51_mean
- D_42_min
- D_50_max
- D_51_last
- S_23_last
- D_64_last
- B_29_min
- D_39_max
- D_45_max
- D_46_last
- D_66_last
- B_11_last
- B_18_min
- S_26_max
- S_26_mean
- D_62_min
- S_9_mean
- R_1_std
- D_46_mean
- B_10_last
- B_4_diff_last_2
- D_59_max
- S_12_std
- D_51_min
- S_11_mean
- B_9_diff_last
- B_17_last
- S_15_mean
- R_27_min
- R_3_last
- D_47_mean
- B_2_mean
- B_29_max
- D_45_mean
- B_29_last
- P_3_std
- S_15_max
- S_9_min
- D_56_max
- D_123_max
- P_2_mean
- B_4_diff_last
- R_3_mean
- B_22_last
- R_5_last
- D_42_max
- B_9_diff_last_2
- D_39_std
- D_121_min
- S_24_last
- B_5_min
- D_65_std
- D_44_std
- D_60_last
- D_48_diff_last_2
- S_5_last
- D_50_mean
- P_2_max
- S_11_max
- B_7_std
- D_47_max
- D_129_last
- R_11_last
- S_9_last
- R_7_last
- D_49_std
- D_120_last
- D_76_last
- D_45_last
- S_3_min
- S_8_mean
- B_21_max
- D_65_mean
- D_59_std
- B_40_max
- R_11_mean
- D_65_max
- D_114_last
- D_47_last
- D_117_last
- S_25_std
- D_118_min
- D_46_min
- P_2_std
- B_40_std
- D_54_last
- S_26_std
- B_14_last
- D_52_last
- D_119_min
- D_56_last
- P_3_max
- D_122_mean
- P_3_mean
- D_44_max
- D_77_max
- D_121_max
- B_23_std
- S_12_mean
- S_8_last
- B_18_mean
- D_129_mean
- P_2_min
- D_144_std
- D_53_last
- D_48_diff_last_3
- B_23_last
- D_91_min
- D_121_mean
- B_2_min
- S_7_last
- S_7_mean
- S_5_std
- D_46_diff_last
- B_17_min
- P_3_last
- D_43_min
- D_132_mean
- S_9_std
- S_5_max
- D_56_mean
- R_26_max
- D_45_min
- D_105_max
- R_4_last
- D_76_max
- D_102_max
- B_7_mean
- B_37_last
- D_142_std
- S_13_max
- B_8_min
- D_75_std
- S_22_std
- D_55_std
- B_9_diff_last_3
- D_128_max
- D_124_last
- B_17_mean
- B_29_std
- B_8_mean
- S_23_std
- S_3_max
- D_121_last
- D_112_min
- B_3_max
- D_118_mean
- D_71_last
- S_8_max
- B_7_diff_last
- B_10_min
- S_24_mean
- D_61_diff_last
- D_132_max
- D_56_min
- S_22_last
- B_9_min
- S_25_last
- D_48_mean
- S_7_diff_last
- D_119_last
- D_46_max
- B_5_max
- D_70_mean
- D_131_std
- B_4_diff_last_3
- D_65_last
- B_10_std
- S_5_mean
- B_24_last
- D_52_min
- D_112_mean
- D_124_max
- D_48_std
- B_3_diff_last
- D_142_max
- D_59_last
- R_12_last
- B_7_diff_last_3
- B_40_last
- S_12_min
- B_40_mean
- D_110_max
- R_26_last
- D_62_last
- D_128_last
- D_50_std
- D_48_max
- S_26_last
- B_37_max
- D_82_last
- R_27_last
- D_63_last
- D_61_mean
- D_52_mean
- S_25_max
- B_6_std
- S_6_mean
- D_77_last
- D_77_min
- D_74_max
- D_77_mean
- R_8_std
- B_5_mean
- D_53_std
- B_28_mean
- D_46_diff_last_2
- B_28_min
- D_140_last
- D_123_mean
- D_141_mean
- S_7_max
- B_13_mean
- D_122_last
- B_25_min
- B_29_mean
- B_17_max
- B_20_last
- S_22_mean
- B_37_mean
- R_1_max
- B_3_diff_last_2
- B_14_std
- R_9_mean
- B_39_min
- D_43_max
- D_62_max
- S_15_min
- D_43_std
- D_41_std
- D_83_std
- D_113_max
- D_44_mean
- D_82_mean
- B_14_max
- B_2_std
- S_8_min
- D_61_last
- D_132_min
- D_102_std
- R_11_std
- S_24_std
- D_41_mean
- P_2_diff_last
- R_16_std
- D_133_max
- D_41_max
- B_33_mean
- D_125_std
- D_71_mean
- D_106_last
- B_4_max
- B_15_std
- S_16_max
- B_25_mean
- D_75_mean
- S_23_diff_last_3
- B_11_std
- D_76_mean
- D_128_mean
- B_21_std
- B_1_std
- B_26_std
- B_15_max
- B_15_last
- S_27_max
- D_76_min
- D_41_diff_last
- B_6_last
- B_5_std
- D_69_max
- S_15_std
- B_12_mean
- S_3_diff_last_3
- B_17_std
- D_47_min
- B_12_max
- D_106_std
- R_8_last
- B_21_mean
- B_16_max
- R_26_mean
- D_58_max
- S_11_last
- D_120_nunique
- B_11_mean
- D_79_std
- D_119_mean
- D_134_mean
- D_61_max
- B_25_last
- P_3_diff_last_3
- D_144_mean
- B_3_diff_last_3
- D_133_mean
- D_74_std
- B_16_min
- B_39_std
- D_55_max
- B_12_std
- D_118_last
- D_54_min
- B_22_mean
- D_111_max
- D_59_mean
- R_12_std
- B_21_last
- P_3_diff_last_2
- S_16_mean
- D_60_mean
- D_141_last
- D_91_last
- S_23_diff_last
- S_17_std
- S_23_diff_last_2
- D_105_diff_last_2
- R_10_last
- D_39_diff_last
- D_105_mean
- D_78_last
- P_3_min
- D_142_mean
- B_39_mean
- B_10_max
- S_27_std
- S_7_std
- B_18_max
- B_38_nunique
- S_6_std
- R_26_std
- D_54_mean
- S_7_diff_last_2
- D_46_diff_last_3
- S_12_last
- B_39_last
- B_13_last
- D_72_mean
- B_24_max
- D_41_diff_last_2
- B_26_mean
- D_62_diff_last_3
- D_108_mean
- D_131_last
- B_16_std
- D_71_std
- D_80_std
- B_2_diff_last
- D_115_max
- B_19_last
- R_14_max
- D_104_std
- S_3_diff_last_2
- S_11_min
- B_40_min
- R_26_min
- B_2_diff_last_2
- R_1_diff_last_2
- S_24_max
- R_9_last
- D_131_max
- B_23_max
- S_22_max
- B_23_min
- D_48_min
- R_6_mean
- D_124_mean
- B_6_min
- S_25_min
- B_24_std
- B_37_min
- R_5_std
- S_23_mean
- B_37_std
- D_110_last
- R_3_max
- B_23_mean
- R_12_min
- D_118_std
- D_63_nunique
- B_2_diff_last_3
- B_41_std
- B_26_last
- D_70_std
- B_20_mean
- B_28_max
- D_61_std
- D_58_mean
- D_128_min
- R_20_last
- D_140_mean
- D_74_min
- R_9_std
- D_105_min
- S_20_std
- D_42_last
- D_134_last
- D_72_std
- D_54_diff_last
- B_10_mean
- B_19_std
- B_32_last
- D_110_min
- D_134_max
- R_1_min
- D_134_min
- D_70_max
- B_7_diff_last_2
- S_12_max
- D_132_last
- B_11_min
- R_21_std
- D_92_std
- D_133_last
- R_27_std
- D_102_min
- D_92_mean
- B_7_max
- D_60_min
- D_104_mean
- D_47_std
- D_49_max
- D_61_min
- S_13_std
- D_115_last
- R_6_max
- D_62_std
- D_60_max
- B_36_mean
- D_121_std
- D_69_mean
- S_26_diff_last_2
- B_36_std
- R_27_mean
- R_27_max
- D_82_std
- S_7_min
- B_28_std
- D_51_std
- R_3_std
- S_3_std
- S_22_min
- D_112_diff_last
- R_12_max
- D_52_std
- D_83_mean
- R_1_diff_last
- D_73_last
- D_41_min
- D_105_diff_last
- D_131_mean
- B_27_last
- B_20_std
- B_20_diff_last_2
- R_14_mean
- D_124_std
- D_73_mean
- D_144_last
- B_39_max
- D_69_last
- D_134_std
- S_27_min
- D_80_last
- B_9_std
- D_83_last
- D_77_std
- D_73_max
- B_25_max
- S_23_min
- P_2_diff_last_2
- D_124_diff_last_3
