fold: 3
params:
  boosting: dart
  learning_rate: 0.01
  objective: binary
  num_leaves: 100
  lambda_l2: 2
  feature_fraction: 0.2
  bagging_fraction: 0.5
  bagging_freq: 10
  min_child_samples: 40
  seed: 42
  verbose: -1
  num_threads: 8
path: res/models/
working: working
name: 3fold_lightgbm_bruteforce_feature_seed3407
result: 3fold_lightgbm_bruteforce_feature_seed3407.pkl
early_stopping_rounds: 1500
num_boost_round: 10500
verbose: 500
loss:
  is_customized: False
  mult_no4prec: 5.0
  max_weights: 2.0