fold: 5
params:
  boosting: dart
  learning_rate: 0.01
  objective: binary
  num_leaves: 100
  lambda_l2: 2
  lambda_l1: 0.0001
  feature_fraction: 0.2
  bagging_fraction: 0.5
  bagging_freq: 10
  min_data_in_leaf: 40
  seed: 3407
  verbose: -1
path: res/models/
working: working
name: 5fold_lightgbm_bruteforce_features_seed3407
result: 5fold_lightgbm_bruteforce_features_seed3407.pkl
early_stopping_rounds: 1500
num_boost_round: 10500
verbose: 500
loss:
  is_customized: False
  mult_no4prec: 5.0
  max_weights: 2.0