fold: 10
params:
  eta: 0.03
  gamma: 1.5
  lambda: 70
  max_depth: 7
  subsample: 0.88
  min_child_weight: 8
  colsample_bytree: 0.5
  seed: 42
  objective: binary:logistic
path: res/models/
name: 10fold_xgb_stacking.pkl
num_boost_round: 10000
early_stopping_rounds: 100
search: False
verbose: 100
