fold: 10
params:
  objective: binary:logistic
  eta: 0.03
  gamma: 1.5
  lambda: 70
  subsample: 0.88
  min_child_weight: 8
  seed: 42
path: res/models/
num_boost_round: 10000
early_stopping_rounds: 75
search: False
verbose: 100
