fold: 10
params:
  reg_alpha: 5.998770177220496e-05
  reg_lambda: 0.07127674208132959
  boosting_type: gbdt
  learning_rate: 0.05
  n_estimators: 10000
  objective: binary
  max_depth: 16
  num_leaves: 128
  colsample_bytree: 0.4241631237880101
  subsample: 0.8876057928391585
  subsample_freq: 5
  min_child_samples: 5
  max_bin: 449
path: res/models/
name: 10fold_lightgbm_pay_features_cross_last_gbdt.pkl
early_stopping_rounds: 1000
search: False
seed: 94
verbose: 250