hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: True
defaults:
  - dataset: dataset
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  