hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: True
output:
  name: output
  nn_preds: 5fold_nn_preds.csv
  lgbm_preds: 10fold_lightgbm_dart.csv
  cb_preds: 10fold_catboost_preds_trick.csv
  xgb_preds: 5fold_xgboost_preds.csv
  gru_preds: 5fold_gru_preds.csv
  ensemble_preds: ensemble_preds.csv
  preds: 3tree_2nn_blend_preds.csv