hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: True
input:
  name: input/amex-default-prediction
  train_labels: train_labels.csv
model:
  path: res/models/
  lgbm_oof: 10fold_lightgbm_pay_features.pkl
  tabnet_oof: train_oof_stacking_tabnet.npy
output:
  name: output
  submission: sample_submission.csv
  nn_preds: 5fold_nn_preds.csv
  lgbm_preds: 10fold_lightgbm_pay_features.csv
  cb_preds: 10fold_catboost_preds_trick.csv
  xgb_preds: 5fold_xgboost_version2.csv
  tabnet_preds: stacking_tabnet.csv
  ensemble_preds: ensemble_preds.csv
  lb_preds: lb_best_ensemble.csv
  preds: gradient_ensemble.csv