hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: True
input:
  name: input/amex-default-prediction
  train_labels: train_labels.csv
models:
  path: res/models/
  lgbm_oof: 5fold_lightgbm_dart_seed42.pkl
  tabnet_oof: 5fold_lightgbm_trick.pkl
output:
  name: output
  submission: sample_submission.csv
  lgbm_preds: 5fold_lightgbm_dart_seed42.csv
  tabnet_preds: 5fold_lightgbm_trick.csv
  ensemble_preds: ensemble_preds.csv
  lb_preds: lb_best_ensemble.csv
  preds: gradient_ensemble.csv