hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: True
input:
  name: input/amex-default-prediction
  train_labels: train_labels.csv
model:
  path: res/models/
  model1_oof: 5fold_lightgbm_time_diff_features_seed42.pkl
  model2_oof: 5fold_lightgbm_gradient_features_seed42.pkl
  model3_oof: 5fold_lightgbm_rate_features_seed42.pkl
  model4_oof: 5fold_lightgbm_rate_features_seed52.pkl
output:
  name: output
  submission: sample_submission.csv
  model1_preds: 5fold_lightgbm_time_diff_features_seed42.csv
  model2_preds: 5fold_lightgbm_gradient_features_seed42.csv
  model3_preds: 5fold_lightgbm_rate_features_seed42.csv
  model4_preds: 5fold_lightgbm_rate_features_seed52.csv
  preds: gradient_ensemble.csv