hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: True
output:
  name: output
  nn_preds: 5fold_nn_preds.csv
  lgbm_preds: 5fold_dart_lightgbm.csv
  cb_preds: 10fold_catboost_preds_seed42.csv
  gru_preds: 5fold_gru_preds.csv
  ensemble_preds: ensemble_preds.csv
  preds: blend_preds.csv