hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: True
input:
  name: input/amex-default-prediction
  train_labels: train_labels.csv
model:
  path: res/models/
  xgb_oof: 10fold_xgboost_stacking.pkl
  tabnet_oof: oof_5fold_tabnet_bruteforce_features_seed3407.csv
  model1_oof: 5fold_lightgbm_bruteforce_features_seed22.pkl
  model2_oof: 5fold_lightgbm_bruteforce_features_seed42.pkl
  model3_oof: 5fold_lightgbm_bruteforce_features_seed99.pkl
  model4_oof: 5fold_lightgbm_bruteforce_features_seed1119.pkl
  model5_oof: 5fold_lightgbm_bruteforce_features_seed3407.pkl
  model6_oof: 5fold_lightgbm_lag_features_seed3407.pkl
  lgbm1_oof: oof_10fold_xgboost_stacking_ver2.csv
  lgbm2_oof: oof_5fold_stacking_gradient.csv
  cb1_oof: oof_5fold_catboost_lag_features_gradient.csv
  cb2_oof: oof_5fold_catboost_cat_features_gradient.csv
output:
  name: output
  submission: sample_submission.csv
  xgb_preds: 10fold_xgboost_stacking.csv
  tabnet_preds: 5fold_tabnet_bruteforce_features_seed3407.csv
  model1_preds: 5fold_lightgbm_bruteforce_features_seed22.csv
  model2_preds: 5fold_lightgbm_bruteforce_features_seed42.csv
  model3_preds: 5fold_lightgbm_bruteforce_features_seed99.csv
  model4_preds: 5fold_lightgbm_bruteforce_features_seed1119.csv
  model5_preds: 5fold_lightgbm_bruteforce_features_seed3407.csv
  model6_preds: 5fold_lightgbm_lag_features_seed3407.csv
  lgbm1_preds: 10fold_xgboost_stacking_ver2.csv
  lgbm2_preds: 5fold_stacking_gradient.csv
  cb1_preds: 5fold_catboost_lag_features_gradient.csv
  cb2_preds: 5fold_catboost_cat_features_gradient.csv
  oof: oof_5fold_stacking_gradient_ver2.csv
  preds: 5fold_stacking_gradient_ver2.csv
score:
  name: log_loss