hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: input/amex-agg-data-f32/
  is_train: false
  test: test_agg_f32_part_credit
  cat_features:
  - B_30_last
  - B_38_last
  - D_114_last
  - D_116_last
  - D_117_last
  - D_120_last
  - D_126_last
  - D_63_last
  - D_64_last
  - D_66_last
  - D_68_last
  encoder: res/data/
model:
  catboost: res/models/10fold_catboost_models.pkl
  lightgbm: res/models/10fold_lightgbm_dart_trick.pkl
  xgboost: res/models/10fold_xgboost_models.pkl
output:
  path: output
  name: 10fold_lightgbm_dart.csv