hydra:
  run:
    dir: ../log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: input/amex-default-prediction/
  is_train: false
  target: target
  train: train_data.ftr
  test: test_data.ftr
  del_features:
  - S_20_last
  - D_96_last
  - D_86_last
  - R_19_last
  - D_94_last
  - R_13_last
  - D_73_last
  - B_27_last
  - D_109_last
  - R_22_last
  features_avg:
  - B_1
  - B_11
  - B_16
  - B_17
  - B_18
  - B_2
  - B_20
  - B_28
  - B_3
  - B_4
  - B_5
  - B_7
  - B_9
  - D_112
  - D_121
  - D_141
  - D_39
  - D_41
  - D_42
  - D_43
  - D_44
  - D_45
  - D_46
  - D_47
  - D_48
  - D_49
  - D_50
  - D_51
  - D_53
  - D_54
  - D_56
  - D_58
  - D_59
  - D_60
  - D_91
  - P_2
  - P_3
  - R_1
  - R_2
  - R_27
  - R_3
  - R_7
  - S_11
  - S_26
  - S_3
  - S_5
  features_last:
  - B_1
  - B_10
  - B_11
  - B_12
  - B_13
  - B_15
  - B_16
  - B_17
  - B_18
  - B_19
  - B_2
  - B_20
  - B_22
  - B_23
  - B_24
  - B_25
  - B_26
  - B_27
  - B_28
  - B_29
  - B_3
  - B_32
  - B_33
  - B_36
  - B_38
  - B_39
  - B_4
  - B_40
  - B_41
  - B_42
  - B_5
  - B_6
  - B_7
  - B_8
  - B_9
  - D_102
  - D_103
  - D_105
  - D_106
  - D_107
  - D_109
  - D_112
  - D_115
  - D_117
  - D_118
  - D_119
  - D_120
  - D_121
  - D_122
  - D_123
  - D_124
  - D_125
  - D_127
  - D_129
  - D_132
  - D_133
  - D_135
  - D_136
  - D_137
  - D_140
  - D_141
  - D_143
  - D_145
  - D_39
  - D_41
  - D_42
  - D_43
  - D_44
  - D_45
  - D_46
  - D_47
  - D_48
  - D_49
  - D_50
  - D_51
  - D_52
  - D_53
  - D_54
  - D_55
  - D_56
  - D_58
  - D_59
  - D_60
  - D_61
  - D_62
  - D_63
  - D_64
  - D_66
  - D_70
  - D_72
  - D_73
  - D_74
  - D_75
  - D_76
  - D_77
  - D_78
  - D_79
  - D_80
  - D_82
  - D_83
  - D_84
  - D_86
  - D_91
  - D_92
  - D_93
  - D_94
  - D_96
  - P_2
  - P_3
  - R_1
  - R_10
  - R_11
  - R_12
  - R_13
  - R_14
  - R_15
  - R_17
  - R_18
  - R_19
  - R_2
  - R_20
  - R_21
  - R_22
  - R_24
  - R_25
  - R_26
  - R_27
  - R_3
  - R_4
  - R_5
  - R_7
  - R_8
  - R_9
  - S_11
  - S_12
  - S_13
  - S_15
  - S_17
  - S_20
  - S_22
  - S_23
  - S_24
  - S_25
  - S_26
  - S_27
  - S_3
  - S_5
  - S_6
  - S_7
  - S_8
  - S_9
  cat_features:
  - B_30
  - B_38
  - D_114
  - D_116
  - D_117
  - D_120
  - D_126
  - D_63
  - D_64
  - D_66
  - D_68
model:
  catboost: res/models/10fold_catboost_models.pkl
  lightgbm: res/models/10fold_lightgbm_avg_models.pkl
  xgboost: res/models/10fold_xgboost_models.pkl
output:
  path: output
  name: 10fold_lightgbm_seed42.csv