hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null

defaults:
  - dataset: dataset
  - features: features
  - logging: wandb
  - models: lgbm

output:
  path: output
  name: 10fold_lightgbm_pay_features_cross_last_gbdt.csv
  submit: sample_submission.csv
  features: features.yaml