hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: input/amex-pay-features/
  test: test_pay_features_part
  drop_features: customer_ID
  selected_features: [
    "P_2_last",
    "B_11-P_2_mean",
    "B_1_last",
    "D_39_last",
    "R_1_last",
    "B_2_last",
    "S_3_mean",
    "B_7_last",
    "B_4_last",
    "B_5_last",
    "B_4_std",
    "S_3_last",
    "B_3_last",
    "D_41_last",
    "B_9_last",
    "D_44_last",
    "D_46_last",
    "B_18_last",
    "B_29_min",
    "D_48_last",
    "D_43_mean",
    "D_43_last",
    "B_11_last",
    "D_50_max",
    "S_26_max",
    "D_42_mean",
    "R_2_last",
    "D_112_std",
    "B_3_std",
    "D_112_last",
    "B_17_last",
    "D_49_last",
    "D_51_min",
    "D_66_last",
    "S_23_last",
    "D_131-P_2_mean",
    "D_45_max",
    "D_59_max",
    "D_62_min",
    "D_51_last",
    "D_42_min",
    "D_51_mean",
    "D_62_mean",
    "D_64_last",
    "S_15_mean",
    "S_11_mean",
    "R_3_last",
    "D_50_last",
    "S_9_mean",
    "S_12_std",
    "R_5_last",
    "D_46_mean",
    "D_121_min",
    "S_23/P_2_std",
    "D_59_std",
    "D_39/P_2_std",
    "B_2_mean",
    "S_24_last",
    "D_131-P_3_mean",
    "D_65_std",
    "S_9_last",
    "R_27_min",
    "P_2_mean",
    "D_42_max",
    "D_123_max",
    "R_3_mean",
    "B_14-P_2_mean",
    "D_77_max",
    "B_8_mean",
    "D_129_mean",
    "S_11_max",
    "S_5_last",
    "B_29_last",
    "D_45_mean",
    "S_8_mean",
    "S_15_max",
    "D_50_mean",
    "S_3_min",
    "D_118_min",
    "D_114_last",
    "B_5_min",
    "B_10_last",
    "B_22_last",
    "S_9_min",
    "D_77_mean",
    "D_129_last",
    "R_11_last",
    "R_1_mean",
    "D_60_last",
    "D_62_last",
    "D_120_last",
    "D_47_mean",
    "B_29_mean",
    "D_39/P_3_std",
    "B_3_max",
    "D_54_last",
    "D_47_max",
    "R_1_max",
    "D_56_max",
    "R_7_last",
    "S_16/P_2_std",
    "R_1_std",
    "D_48_mean",
    "D_47_last",
    "S_26_mean",
    "B_14-P_2_std",
    "D_39_max",
    "B_14_last",
    "D_49_std",
    "B_11/P_2_std",
    "D_76_last",
    "R_11_mean",
    "D_39xP_2_std",
    "P_2_max",
    "B_37_last",
    "D_56_mean",
    "D_52_min",
    "D_44_std",
    "P_3_last",
    "D_122_mean",
    "B_23_last",
    "R_27_last",
    "S_12_mean",
    "D_45_last",
    "D_117_last",
    "B_40_max",
    "D_65_max",
    "B_10_std",
    "D_71_last",
    "D_52_last",
    "S_7_last",
    "D_56_min",
    "B_18_min",
    "S_8_last",
    "D_144_std",
    "S_22_last",
    "B_9_mean",
    "D_53_last",
    "B_15_max",
    "D_52_mean",
    "D_65_mean",
    "S_22_std",
    "B_40_std",
    "D_75_std",
    "B_17/P_2_mean",
    "D_132_max",
    "D_91_min",
    "S_16-P_2_std",
    "S_5_max",
    "S_3_max",
    "P_3_max",
    "B_2_min",
    "D_65_last",
    "D_128_max",
    "S_25_std",
    "B_14-P_3_std",
    "D_51_max",
    "D_123_std",
    "R_4_last",
    "B_18_mean",
    "B_24_last",
    "D_128_mean",
    "S_8_max",
    "D_39_std",
    "B_11xP_3_std",
    "D_124_max",
    "D_44_max",
    "B_20_last",
    "D_102_max",
    "D_105_max",
    "B_40_last",
    "S_23-P_2_std",
    "R_26_max",
    "B_29_max",
    "D_76_mean",
    "P_2_min",
    "D_118_mean",
    "D_121_max",
    "B_14/P_2_mean",
    "D_61_mean",
    "S_15_std",
    "D_46_min",
    "D_133_max",
    "D_43_max",
    "D_121_last",
    "B_11/P_3_std",
    "B_7_std",
    "D_70_mean",
    "D_39-P_2_mean",
    "D_45_min",
    "S_16-P_3_mean",
    "B_13_mean",
    "R_3_max",
    "D_119_min",
    "D_39-P_3_std",
    "S_11_last",
    "S_26_last",
    "D_121_mean",
    "D_112_mean",
    "D_75_mean",
    "S_26_std",
    "S_9_std",
    "B_14/P_2_std",
    "B_38_last",
    "D_132_min",
    "D_82_last",
    "B_28_min",
    "D_77_last",
    "B_16_max",
    "D_127_last",
    "D_131-P_3_std",
    "D_48_std",
    "S_23-P_3_std",
    "D_76_max",
    "D_47_min",
    "B_26_last",
    "S_23xP_2_std",
    "D_63_last",
    "S_15_last",
    "S_7_mean",
    "B_21_max",
    "D_140_last",
    "B_5_mean",
    "B_5_max",
    "D_122_last",
    "D_134_max",
    "D_124_last",
    "B_11/P_2_mean",
    "D_125_std",
    "D_123_mean",
    "S_25_max",
    "S_23/P_2_mean",
    "S_23xP_3_std",
    "B_11-P_2_std",
    "D_60_max",
    "D_110_max",
    "S_22_mean",
    "D_52_max",
    "B_6_min",
    "B_17xP_2_mean",
    "D_43_std",
    "S_12_min",
    "B_22_mean",
    "D_55_std",
    "D_141_mean",
    "D_126_nunique",
    "B_26_std",
    "S_12_last",
    "S_25_last",
    "B_4_max",
    "D_81_std",
    "S_7_max",
    "D_41_max",
    "B_16_mean",
    "D_142_max",
    "B_21_mean",
    "D_62_max",
    "B_10_min",
    "B_17_mean",
    "D_80_last",
    "D_142_std",
    "D_41_mean",
    "B_17-P_3_std",
    "B_2_std",
    "S_24_mean",
    "D_39xP_3_std",
    "D_113_max",
    "B_20_mean",
    "B_16_last",
    "B_24_std",
    "D_39-P_3_mean",
    "B_17-P_3_mean",
    "D_119_max",
    "D_53_std",
    "D_119_mean",
    "B_7_max",
    "D_118_last",
    "D_72_mean",
    "R_26_last",
    "D_39-P_2_std",
    "B_21_last",
    "D_131/P_2_std",
    "S_6_mean",
    "S_7_std",
    "S_6_std",
    "R_9_min",
    "D_46_max",
    "D_72_std",
    "D_132_last",
    "D_142_min",
    "S_13_max",
    "S_5_std",
    "D_70_std",
    "D_58_mean",
    "B_17_min",
    "B_14_max",
    "S_12_max",
    "R_9_mean",
    "B_10_max",
    "S_8_std",
    "S_24_std",
    "B_33_std",
    "D_82_mean",
    "B_28_max",
    "B_6_last",
    "D_106_std",
    "R_12_last",
    "D_105_mean",
    "P_3_min",
    "S_13_last",
    "D_108_mean",
    "B_18_max",
    "D_106_last",
    "D_70_last",
    "D_132_mean",
    "B_39_last",
    "B_16_min",
    "D_122_min",
    "S_9_max",
    "B_28_mean",
    "D_102_std",
    "D_59_last",
    "B_33_mean",
    "S_22_min",
    "B_20_max",
    "B_2_max",
    "D_78_last",
    "B_19_std",
    "D_105_last",
    "R_6_last",
    "D_74_max",
    "D_124_min",
    "R_10_std",
    "D_48_max",
    "D_61_last",
    "D_46_std",
    "D_55_mean",
    "D_134_min",
    "D_74_std",
    "B_36_std",
    "S_16-P_3_std",
    "D_49_max",
    "B_17-P_2_mean",
    "B_13_std",
    "R_8_last",
    "B_10_mean",
    "B_15_last",
    "D_119_last",
    "D_42_last",
    "D_39xP_3_mean",
    "D_43_min",
    "S_16-P_2_mean",
    "R_5_max",
    "S_27_max",
    "B_17xP_2_std",
    "S_13_mean",
    "D_54_mean",
    "B_25_last",
    "B_11-P_3_mean",
    "D_140_mean",
    "R_12_std",
    "D_56_last",
    "R_6_max",
    "B_11_mean",
    "S_16/P_2_mean",
    "D_69_last",
    "R_27_max",
    "D_54_min",
    "D_80_mean",
    "R_10_last",
    "B_21_std",
    "B_5_std",
    "D_91_last",
    "P_4_std",
    "S_7_min",
    "D_50_min",
    "B_17xP_3_mean",
    "D_59_mean",
    "R_9_max",
    "B_15_min",
    "D_134_mean",
    "S_27_mean",
    "R_26_std",
    "B_17_std",
    "S_15_min",
    "B_14xP_3_mean",
    "D_115_min",
    "D_133_last",
    "R_16_last",
    "D_39xP_2_mean",
    "B_12_mean",
    "S_23-P_2_mean",
    "D_61_min",
    "B_16_std",
    "R_15_std",
    "B_19_max",
    "D_124_std",
    "D_77_std",
    "R_3_std",
    "D_131-P_2_std",
    "D_62_std",
    "S_16xP_2_mean",
    "R_15_mean",
    "D_142_last",
    "R_11_std",
    "B_14xP_3_std",
    "D_115_last",
    "R_8_mean",
    "D_71_min",
    "D_139_mean",
    "R_5_std",
    "B_6_mean",
    "D_74_last",
    "B_15_std",
    "D_61_std",
    "S_27_min",
    "B_25_max",
    "D_133_std",
    "D_58_last",
    "D_41_std",
    "B_25_min",
    "S_16_mean",
    "S_20_std",
    "R_8_std",
    "B_14xP_2_std",
    "B_26_mean",
    "B_14_min",
    "B_11/P_3_mean",
    "D_140_std",
    "D_142_mean",
    "S_16xP_2_std",
    "B_24_mean",
    "B_31_last",
    "D_61_max",
    "S_27_last",
    "D_110_last",
    "R_14_mean",
    "D_73_mean",
    "B_11-P_3_std",
    "D_83_last",
    "B_6_max",
    "R_14_max",
    "D_131xP_2_mean",
    "D_71_mean",
    "B_36_last",
    "R_20_last",
    "D_39/P_2_mean",
    "R_14_last",
    "B_36_max",
    "D_69_mean",
    "D_111_max",
    "D_41_min",
    "D_92_std",
    "D_70_min",
    "D_144_min",
    "R_14_std",
    "D_118_max",
    "D_39_min",
    "D_49_mean",
    "D_69_std",
    "S_16xP_3_mean",
    "R_7_mean",
    "D_79_max",
    "D_111_mean",
    "B_17-P_2_std",
    "R_12_mean",
    "D_122_std",
    "D_115_std",
    "B_1_min",
    "R_12_max",
    "S_27_std",
    "B_29_std",
    "R_13_mean",
    "S_16/P_3_std",
    "B_28_last",
    "D_138_last",
    "S_11_std",
    "B_26_max",
    "D_134_last",
    "B_11_max",
    "D_111_std",
    "B_6_std",
    "B_1_max",
    "D_48_min",
    "S_22_max",
    "B_26_min",
    "D_106_mean",
    "D_135_std",
    "D_58_std",
  ]
  cat_features:
  - B_30_last
  - B_38_last
  - D_114_last
  - D_116_last
  - D_117_last
  - D_120_last
  - D_126_last
  - D_63_last
  - D_64_last
  - D_66_last
  - D_68_last
  - B_30_nunique
  - B_38_nunique
  - D_114_nunique
  - D_116_nunique
  - D_117_nunique
  - D_120_nunique
  - D_126_nunique
  - D_63_nunique
  - D_64_nunique
  - D_66_nunique
  - D_68_nunique
  - B_30_count
  - B_38_count
  - D_114_count
  - D_116_count
  - D_117_count
  - D_120_count
  - D_126_count
  - D_63_count
  - D_64_count
  - D_66_count
  - D_68_count
  encoder: res/data/
model:
  path: res/models/
  name: 10fold_lightgbm_pay_features_ratio.pkl
output:
  path: output
  name: 10fold_lightgbm_pay_features_ratio.csv
  submit: sample_submission.csv
