hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: input/amex-agg-data-f32/
  test: test_agg_f32_credit
  drop_features: customer_ID
  cat_features:
  - B_30_last
  - B_38_last
  - D_114_last
  - D_116_last
  - D_117_last
  - D_120_last
  - D_126_last
  - D_63_last
  - D_64_last
  - D_66_last
  - D_68_last
  encoder: res/data/
model:
  path: res/models/
  name: 10fold_lightgbm_dart_trick_credit.pkl
output:
  path: output
  name: 10fold_lightgbm_dart_trick_credit.csv
  submit: sample_submission.csv
