hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null

defaults:
  - dataset: dataset
  - features: time_features
  - logger: wandb
  - model: lgbm

output:
  path: output
  name: 5fold_lightgbm_trick_features_seed42.csv
  submit: sample_submission.csv
  features: features.yaml