hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null

defaults:
  - dataset: dataset
  - features: features
  - logger: wandb
  - model: lightgbm

output:
  path: output
  name: 5fold_lightgbm_shap_features_seed22.csv
  submit: sample_submission.csv
  features: features.yaml
