hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  submit_path: input/amex-default-prediction/
  submit: sample_submission.csv
  path: input/amex-agg-data-f32/
  is_train: false
  test: test_agg_f32_part
  drop_features: customer_ID
  cat_features:
  - B_30_last
  - B_38_last
  - D_114_last
  - D_116_last
  - D_117_last
  - D_120_last
  - D_126_last
  - D_63_last
  - D_64_last
  - D_66_last
  - D_68_last
  encoder: res/data/
model: res/models/10fold_lightgbm_dart_trick.pkl
output:
  path: output
  name: 10fold_lightgbm_dart.csv