hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: input/amex-agg-data-f32/
  test: test_agg_f32_part_credit
  drop_features: customer_ID
  cat_features:
  - B_30_last
  - B_38_last
  - D_114_last
  - D_116_last
  - D_117_last
  - D_120_last
  - D_126_last
  - D_63_last
  - D_64_last
  - D_66_last
  - D_68_last
  select_features: [
    'CS', 'B_5_last', 'D_39_last', 'B_2_last', 'D_46_last', 
    'D_49_last', 'D_112_std', 'B_4_std', 'B_29_min', 'S_15_mean', 
    'D_64_last', 'B_2_mean', 'B_11_last', 'B_3_std', 'B_3_last', 
    'D_50_max', 'D_59_max', 'S_26_max', 'D_39_max', 'B_4_last', 
    'D_62_min', 'D_120_last', 'P_2_mean', 'D_62_mean', 'S_12_std', 
    'D_50_last', 'R_5_last', 'D_42_mean', 'S_26_std', 'D_44_std', 
    'B_40_std', 'D_66_last', 'S_11_mean', 'S_9_mean', 'B_1_last', 
    'D_121_max', 'D_43_last', 'D_42_min', 'S_9_last', 'B_9_last', 
    'D_63_last', 'D_39_std', 'D_121_min', 'D_66_count', 'B_29_mean', 
    'S_11_max', 'S_6_last', 'B_18_mean', 'S_5_last', 'D_118_min', 
    'D_50_mean', 'B_14_last', 'R_1_max', 'D_56_min', 'B_23_min', 
    'B_7_std', 'D_42_max', 'S_3_mean', 'D_53_last', 'D_46_mean', 
    'S_25_std', 'P_3_max', 'D_129_mean', 'P_2_last', 'D_123_mean', 
    'R_11_last', 'D_44_last', 'R_1_std', 'B_18_min', 'D_77_mean', 
    'R_27_min', 'S_7_last', 'D_60_last', 'S_8_mean', 'R_26_max', 
    'D_144_std', 'B_17_last', 'S_5_std', 'D_46_min', 'D_54_last', 
    'S_12_mean', 'S_8_max', 'B_40_max', 'D_114_last', 'R_3_mean', 
    'D_59_std', 'D_129_last', 'D_117_last', 'B_29_max', 'P_2_min', 
    'R_11_mean', 'D_47_mean', 'B_21_max', 'D_41_std', 'D_124_max', 
    'B_10_std', 'B_2_min', 'D_72_mean', 'D_76_max', 'D_119_min', 
    'S_22_std', 'D_76_last', 'B_7_last', 'D_123_std', 'D_47_max', 
    'B_23_std', 'S_12_min', 'S_24_last', 'B_28_min', 'S_9_min', 
    'D_65_max', 'D_121_mean', 'R_6_last', 'D_52_mean', 'B_29_std', 
    'P_3_mean', 'D_105_max', 'D_48_std', 'S_22_last', 'B_10_min', 
    'B_5_min', 'D_62_max', 'B_28_last', 'D_122_last', 'R_27_last', 
    'S_24_min', 'D_102_max', 'S_26_mean', 'R_3_last', 'D_122_mean',
    'B_29_last', 'D_102_std', 'B_24_last', 'S_23_mean', 'B_18_std',
    'D_133_max', 'D_79_std', 'D_132_mean', 'R_6_max', 'B_23_last', 
    'D_71_last', 'B_17_mean', 'D_132_max', 'S_9_max', 'S_5_max',
    'D_140_last', 'D_56_max', 'D_91_min', 'D_61_max', 'S_7_std',
    'S_3_min', 'B_3_max', 'P_2_std', 'B_40_last', 'D_132_min', 
    'D_77_max', 'D_58_last', 'B_16_max', 'P_2_max', 'B_5_std', 
    'S_9_std', 'D_60_max', 'S_6_mean', 'D_124_min', 'D_76_min', 
    'D_128_mean', 'B_14_std', 'D_52_last', 'R_26_last', 'P_3_std', 
    'D_56_mean', 'D_82_max', 'B_33_mean', 'D_76_mean', 'D_104_std', 
    'B_4_min', 'S_12_max', 'D_49_std', 'D_47_min', 'D_49_min', 
    'B_17_std', 'D_75_std', 'D_65_std', 'D_78_max', 'D_51_mean', 
    'D_45_mean', 'D_79_last', 'S_3_last', 'D_48_last', 'D_80_last',
    'D_52_min', 'S_11_last', 'D_70_std', 'B_13_mean', 'D_141_mean', 
    'S_26_last', 'B_17_min', 'D_61_std', 'D_124_mean', 'D_145_mean', 
    'D_115_mean', 'B_25_last', 'B_16_min', 'D_44_mean', 'R_9_std', 
    'D_54_min', 'R_16_std', 'D_48_min', 'R_10_last', 'S_3_max', 
    'D_59_mean', 'D_48_mean', 'B_11_std', 'S_24_std', 'S_25_max', 
    'B_28_std', 'R_8_std', 'R_26_mean', 'D_65_mean', 'D_118_mean',
    'B_21_mean', 'B_6_min', 'B_9_mean', 'B_1_std', 'D_112_min', 
    'D_82_mean', 'D_113_mean', 'S_25_last', 'B_11_mean', 'R_1_mean', 
    'D_48_max', 'D_119_max', 'S_8_last', 'B_4_max', 'D_55_min', 'D_47_last', 
    'B_15_max', 'D_46_std', 'S_15_min', 'B_13_max', 'D_123_max', 'B_39_max', 
    'B_7_max', 'S_16_max', 'D_119_mean', 'D_54_std', 'D_50_min', 'S_23_std', 
    'B_37_std', 'D_43_max', 'D_49_mean', 'S_13_max', 'B_2_std', 'D_78_last', 
    'B_12_std', 'B_20_last', 'D_58_min', 'D_59_min', 'S_3_std', 'B_6_last', 
    'R_9_mean', 'D_115_std', 'D_74_min', 'B_21_std', 'D_62_last', 'R_11_std',
    'D_74_std', 'D_39_mean', 'D_112_mean', 'D_50_std', 'S_24_mean', 'D_70_mean', 
    'R_12_std', 'R_2_last', 'D_41_min', 'R_19_last', 'D_45_max', 'D_82_std', 
    'D_142_std', 'D_84_last', 'D_60_min', 'D_53_max', 'D_63_nunique', 
    'B_8_std', 'S_22_mean', 'D_142_last', 'D_61_mean', 'D_60_mean', 
    'B_15_last', 'D_110_max', 'D_75_mean', 'S_27_std', 'R_14_max', 
    'D_53_min', 'B_28_mean', 'D_56_last', 'D_133_std', 'D_76_std', 
    'B_6_std', 'D_106_mean', 'R_10_std', 'R_26_std', 'B_16_last', 
    'S_17_std', 'R_1_last', 'B_5_max', 'P_4_std', 'D_107_std', 'B_19_mean', 
    'B_37_last', 'B_13_last', 'D_55_std', 'D_83_last', 'D_46_max', 'D_141_max', 
    'B_40_mean', 'D_121_last', 'D_41_last', 'D_110_std', 'D_56_std', 'D_142_min',
    'D_102_mean', 'D_92_std', 'D_110_mean', 'D_134_min', 'B_20_mean', 'D_105_min', 
    'S_5_mean', 'P_3_min', 'B_9_max', 'D_58_std', 'B_36_std', 'S_18_mean', 'R_16_last',
    'R_3_max', 'B_9_min', 'D_134_max', 'R_9_max', 'S_7_max', 'D_118_max', 'D_134_mean', 
    'D_43_std', 'B_2_max', 'B_15_mean', 'R_14_mean', 'S_7_min', 'R_5_std', 'B_1_min', 
    'S_15_max', 'D_141_std', 'R_27_std', 'R_27_mean', 'D_129_std', 'S_12_last', 
    'D_45_last', 'D_115_last', 'D_58_max', 'D_106_min', 'S_13_last', 'R_13_std', 
    'D_142_max', 'B_24_max', 'S_16_std', 'B_14_max', 'D_69_last', 'D_129_min', 
    'D_69_mean', 'R_3_std', 'D_74_mean', 'D_62_std', 'D_105_std', 'D_55_last', 
    'S_23_last', 'R_18_std', 'B_5_mean', 'D_42_last', 'S_11_min', 'B_19_max',
    'D_61_min', 'D_106_std', 'B_26_max', 'S_25_min', 'B_10_last', 'D_125_std', 
    'D_49_max', 'P_4_min', 'D_53_std', 'D_103_mean', 'D_43_mean', 'B_38_nunique', 
    'D_75_last', 'B_39_mean', 'D_83_min', 'D_139_max', 'S_20_std', 'D_105_mean', 
    'B_10_max', 'D_72_last', 'R_12_last', 'D_110_min', 'S_16_mean', 'B_38_last', 
    'B_10_mean', 'B_39_last', 'B_14_mean', 'B_40_min', 'D_138_mean', 'D_68_last', 
    'D_72_std', 'P_3_last', 'D_124_last', 'B_6_mean', 'R_19_std', 'D_110_last', 
    'S_7_mean', 'B_9_std', 'D_132_last', 'B_16_std', 'S_22_min', 'B_17_max', 
    'S_20_mean', 'D_60_std', 'R_15_std', 'D_136_std', 'R_23_std', 'D_140_mean', 
    'D_145_std', 'D_54_mean', 'D_130_std', 'S_27_mean', 'S_13_mean', 'D_72_max', 
    'B_18_max', 'B_28_max', 'B_12_last', 'R_7_std', 'D_126_nunique', 'D_55_mean', 
    'S_6_std', 'D_92_mean', 'D_69_max', 'S_23_max', 'B_25_max', 'D_122_std', 'B_7_mean', 
    'D_75_max', 'D_78_std', 'D_121_std', 'B_37_max', 'B_32_last', 'D_127_std', 'S_8_min', 
    'R_12_mean', 'B_11_min', 'D_77_min', 'D_136_max', 'D_69_min', 'R_19_max', 'S_18_std', 
    'R_3_min', 'B_26_std', 'R_6_std', 'S_13_min', 'B_7_min', 'R_21_std', 'D_77_last', 
    'D_69_std', 'S_27_max', 'D_115_min', 'D_134_last', 'D_111_last', 'D_96_std', 
    'D_93_std', 'D_80_mean', 'D_119_std', 'B_24_std', 'D_115_max', 'D_89_std', 
    'D_51_std', 'D_118_last', 'D_113_min', 'B_41_std', 'B_12_mean', 'D_135_std', 
    'D_105_last', 'D_41_mean', 'B_19_min', 'D_135_mean', 'D_84_std', 'D_86_std', 
    'D_141_last', 'B_33_std', 'D_94_last', 'S_17_last', 'S_23_min', 'D_81_std', 
    'D_51_last', 'S_24_max', 'D_132_std', 'S_27_last', 'B_41_max', 'D_75_min', 
    'B_20_std', 'D_91_std', 'S_11_std', 'S_17_max', 'R_16_max', 'D_109_std', 
    'R_20_last', 'D_127_mean', 'D_47_std', 'D_83_std', 'D_61_last'
  ]
  encoder: res/data/
model:
  path: res/models/
  name: 10fold_lightgbm_trick_credit.pkl
output:
  path: output
  name: 10fold_lightgbm_trick_credit.csv
  submit: sample_submission.csv