hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null

defaults:
  - dataset: dataset
  - features: features
  - logger: wandb
  - model: lightgbm

output:
  model: dart
  path: output
  name: 5fold_lightgbm_custom_features_seed99.csv
  submit: sample_submission.csv
  features: features.yaml
