hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: True
output:
  name: output
  submission: sample_submission.csv
  model1_preds: ensemble_gradient_lightgbm.csv
  model2_preds: test_lgbm_baseline_5fold_seed_blend.csv
  model3_preds: 5fold_lightgbm_statement_features_gradient.csv
  preds: rank_blend_statement.csv
