hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: True
dataset:
  path: input/amex-default-prediction
  train: train_labels.csv
  drop_features: customer_ID
  target: target
output:
  credit_select: 10fold_lightgbm_credit_select.pkl
  credit: 10fold_lightgbm_credit.pkl
  trick_credit: 10fold_lightgbm_trick_credit.pkl
  trick_select: 10fold_lightgbm_trick_select.pkl
experiment:
  project: amex-default-prediction
  entity: ds-wook
  name: lightgbm_stacking_1
model:
  fold: 10
  params:
    reg_alpha: 5.998770177220496e-05
    reg_lambda: 0.07127674208132959
    boosting_type: gbdt
    learning_rate: 0.05
    n_estimators: 2500
    objective: binary
    max_depth: 16
    num_leaves: 128
    colsample_bytree: 0.4241631237880101
    subsample: 0.8876057928391585
    subsample_freq: 5
    min_child_samples: 5
    max_bin: 449
  path: res/models/
  name: 10fold_lightgbm_stacking.pkl
  early_stopping_rounds: 200
  search: False
  seed: 42
  verbose: 100