hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: input/amex-default-prediction/
  is_train: true
  target: target
  train: train_agg.pkl
  test: test_agg.pkl
  cat_features:
  - B_30_last
  - B_38_last
  - D_114_last
  - D_116_last
  - D_117_last
  - D_120_last
  - D_126_last
  - D_63_last
  - D_64_last
  - D_66_last
  - D_68_last
experiment:
  project: amex-default-prediction
  entity: ds-wook
  name: catboost_1
  tags:
  - CatBoost
model:
  fold: 5
  params:
    learning_rate: 0.05
    eval_metric: Logloss
    loss_function: Logloss
    iterations: 10000
    one_hot_max_size: 4
    used_ram_limit: 4gb
    task_type: CPU
  path: res/models/5fold_catboost.pkl
  search: False
  seed: 42
  verbose: 100