hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: input/amex-default-prediction/
  target: target
  train: train_data.ftr
  test: test_data.ftr
  is_catboost: False
  cat_features:
  - B_30
  - B_38
  - D_114
  - D_116
  - D_117
  - D_120
  - D_126
  - D_63
  - D_64
  - D_66
  - D_68
experiment:
  project: amex-default-prediction
  entity: ds-wook
  name: lightgbm_1
  tags:
  - LightGBM
model:
  fold: 10
  params:
    boosting_type: gbdt
    learning_rate: 0.05
    n_estimators: 10000
    objective: binary
    reg_alpha: 5.998770177220496e-05
    reg_lambda: 0.07127674208132959
    max_depth: 18
    num_leaves: 125
    colsample_bytree: 0.4241631237880101
    subsample: 0.8876057928391585
    subsample_freq: 5
    min_child_samples: 5
    max_bin: 449
  path: res/models/10fold_lightgbm_models.pkl
  metric: logloss
  early_stopping_rounds: 100
  search: False
  seed: 42
  verbose: 100
