hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: input/amex-pay-features/
  is_train: true
  target: target
  train: train_pay_features.pkl
  test: test_pay_features_part
  drop_features: customer_ID
  selected_features: ['P_2_last', 'B_11-P_2_mean', 'B_1_last', 'D_39_last', 'S_3_mean', 'R_1_last', 'B_4_last', 'B_2_last', 'B_7_last', 'B_5_last', 'B_3_last', 'B_4_std', 'B_9_last', 'S_3_last', 'D_41_last', 'B_11_last', 'D_44_last', 'D_46_last', 'B_18_last', 'D_62_mean', 'B_29_min', 'D_43_mean', 'D_43_last', 'B_3_std', 'D_112_last', 'S_26_max', 'D_42_mean', 'D_48_last', 'R_2_last', 'D_112_std', 'D_51_min', 'S_23_last', 'B_17_last', 'D_51_mean', 'D_49_last', 'D_50_max', 'D_42_min', 'D_64_last', 'D_59_max', 'S_15_mean', 'D_50_last_2', 'R_1_max', 'D_45_max', 'B_2_mean', 'D_131-P_2_mean', 'D_62_min', 'R_1_mean', 'D_39/P_2_std', 'S_24_last', 'S_11_mean', 'B_2_last_2', 'D_123_max', 'D_131-P_3_mean', 'D_66_last', 'S_9_mean', 'R_27_min', 'R_3_last', 'B_3_max', 'D_51_last', 'S_5_last', 'D_45_mean', 'R_5_last', 'D_46_mean', 'S_23/P_2_std', 'S_12_std', 'R_3_mean', 'B_29_mean', 'D_47_last', 'D_118_min', 'D_47_mean', 'S_9_last', 'B_14-P_2_mean', 'D_120_last', 'S_11_max', 'D_122_mean', 'R_11_last', 'B_18_mean', 'D_56_last_3', 'D_42_max', 'S_15_max', 'D_117_last', 'D_50_last_3', 'D_121_min', 'D_59_std', 'S_3_min', 'B_22_last', 'D_76_last', 'D_49_std', 'D_65_std', 'B_29_last_3', 'D_39_max', 'R_7_last', 'B_11/P_2_std', 'P_2_mean', 'R_4_last', 'B_8_mean', 'S_16-P_2_std', 'B_40_std', 'S_26_mean', 'D_52_min', 'D_39/P_3_std', 'D_65_mean', 'D_54_last', 'B_29_last_2', 'D_129_mean', 'S_12_mean', 'B_23_last', 'D_56_last_2', 'D_60_last', 'B_7_std', 'P_2_max', 'D_62_last', 'D_44_std', 'D_77_mean', 'D_119_min', 'D_52_last', 'D_46_min', 'D_47_max', 'S_7_last', 'D_45_last', 'S_8_max', 'B_5_last_2', 'B_5_min', 'B_14_last', 'B_14-P_2_std', 'D_45_last_3', 'D_52_mean', 'D_121_max', 'D_66_last_3', 'D_56_min', 'D_121_mean', 'S_16/P_2_std', 'B_17/P_2_mean', 'B_10_std', 'R_27_last', 'B_18_min', 'D_121_last_3', 'D_50_mean', 'P_3_max', 'D_50_last', 'D_39_last_2', 'S_9_std', 'D_129_last', 'S_8_mean', 'B_10_last', 'P_3_last', 'S_9_min', 'D_62_last_3', 'B_24_last', 'D_144_std', 'D_102_max', 'S_13_max', 'B_37_last', 'B_40_max', 'R_11_mean', 'B_5_last_3', 'D_43_last_2', 'B_9_mean', 'D_82_last', 'D_105_max', 'R_1_last_2', 'S_22_std', 'D_48_std', 'D_65_max', 'D_132_max', 'B_2_std', 'B_9_last_3', 'S_5_std', 'B_21_max', 'D_55_std', 'D_133_max', 'D_91_last', 'S_8_last', 'B_5_max', 'D_44_max', 'D_39-P_3_std', 'S_12_min', 'B_15_max', 'D_47_last_2', 'P_2_last_3', 'S_26_std', 'D_91_min', 'D_132_last_2', 'D_71_last', 'S_7_max', 'S_5_max', 'D_47_last_3', 'S_16-P_3_mean', 'S_13_mean', 'B_40_last', 'D_75_std', 'R_26_max', 'P_2_last_2', 'D_123_std', 'B_28_min', 'D_65_last', 'B_10_min', 'D_45_last_2', 'D_76_max', 'S_16-P_2_mean', 'D_39-P_2_mean', 'B_14/P_2_std', 'S_23-P_3_std', 'D_124_last', 'D_141_mean', 'S_24_max', 'D_114_last_2', 'D_63_last', 'B_37_std', 'S_11_last', 'D_124_max', 'S_26_last_2', 'B_20_last', 'S_12_max', 'D_42_last_2', 'S_15_min', 'D_112_mean', 'B_18_std', 'B_13_min', 'D_142_std', 'D_77_last_2', 'D_70_mean', 'B_3_last_2', 'S_3_max', 'B_13_mean', 'D_41_std', 'B_14-P_3_std', 'D_77_max', 'B_20_mean', 'D_82_mean', 'B_2_last_3', 'S_25_std', 'D_39_std', 'S_23-P_2_std', 'D_113_max', 'B_22_mean', 'D_39-P_2_std', 'D_52_last_3', 'B_7_last_2', 'B_2_min', 'D_45_min', 'R_3_max', 'B_15_last', 'R_26_mean', 'B_17_mean', 'D_119_mean', 'B_17-P_3_std', 'D_131/P_3_std', 'D_77_last', 'D_77_min', 'D_140_last', 'B_17-P_2_mean', 'S_3_last_2', 'B_37_max', 'D_43_std', 'P_2_min', 'S_3_std', 'B_10_mean', 'S_16-P_3_std', 'B_25_last_3', 'R_9_mean', 'D_125_std', 'D_119_last', 'B_18_max', 'D_142_last_2', 'D_128_max', 'D_76_mean', 'B_26_last', 'B_4_max', 'D_56_last', 'S_22_mean', 'D_132_min', 'B_16_last', 'D_61_mean', 'D_56_mean', 'R_6_max', 'B_11/P_3_std', 'D_52_last_2', 'S_23/P_2_mean', 'D_60_last_2', 'D_43_min', 'B_17-P_3_mean', 'D_132_mean', 'D_59_last', 'R_5_std', 'D_134_min', 'B_16_min', 'B_11-P_2_std', 'B_6_last_3', 'D_66_last_2', 'D_118_mean', 'D_128_mean', 'B_14_last_3', 'S_11_last_3', 'D_61_last', 'B_14/P_2_mean', 'S_25_last', 'D_119_last_3', 'B_5_mean', 'D_78_last', 'B_12_last', 'D_52_max', 'S_7_last_2', 'S_15_last_2', 'D_59_mean', 'S_12_last_2', 'D_115_last_3', 'S_24_min', 'D_110_max', 'S_26_last_3', 'D_114_last', 'D_39/P_3_mean', 'D_46_max', 'D_47_min', 'B_9_min', 'D_61_min', 'B_16_max', 'B_21_std', 'D_70_std', 'D_56_max', 'S_23-P_2_mean', 'B_33_mean', 'D_140_mean', 'D_144_mean', 'B_17_min', 'B_17-P_2_std', 'S_22_last', 'R_7_last_2', 'S_24_std', 'B_14-P_3_mean', 'D_106_last', 'D_70_max', 'S_25_max', 'D_60_max', 'R_8_std', 'S_25_last_2', 'D_142_max', 'B_28_mean', 'B_11_mean', 'S_15_last', 'D_134_max', 'B_20_max', 'D_132_last', 'B_37_min', 'R_11_std', 'S_24_mean', 'D_42_last', 'D_106_std', 'R_16_last_2', 'B_39_min', 'R_16_mean', 'B_10_max', 'B_13_last_3', 'B_23_std', 'D_59_last_2', 'D_75_last', 'B_16_last_2', 'D_117_last_2', 'B_16_std', 'D_54_min', 'D_133_mean', 'B_25_max', 'R_3_std', 'R_1_std', 'D_55_last_2', 'B_24_max', 'D_70_last', 'B_5_std', 'R_27_last_3', 'R_12_last', 'B_23_max', 'D_60_min', 'D_104_max', 'D_131/P_2_std', 'D_55_min', 'D_80_last_2', 'D_71_max', 'D_46_last_2', 'S_5_mean', 'S_25_mean', 'D_41_max', 'R_3_last_2', 'B_25_mean', 'D_58_mean', 'D_121_last_2', 'D_142_last_3', 'B_15_std', 'B_11_last_3', 'B_40_mean', 'D_63_nunique', 'R_26_std', 'B_20_std', 'B_26_mean', 'S_16/P_2_mean', 'B_22_last_2', 'R_16_last', 'D_49_last_2', 'B_13_max', 'D_104_last_2', 'D_54_mean', 'D_118_last_2', 'R_10_std', 'B_28_last_3', 'D_51_last_2', 'B_21_mean', 'D_124_std', 'R_27_last_2', 'D_60_last_3', 'D_129_last_2', 'D_53_max', 'D_43_max', 'B_16_mean', 'D_61_std', 'D_133_last', 'D_103_std', 'S_23_last_3', 'D_141_max', 'D_72_std', 'D_143_mean', 'P_4_last', 'B_40_last_2', 'D_43_last_3', 'S_22_min', 'R_8_last', 'R_12_std', 'B_12_max', 'B_26_last_2', 'S_7_std', 'R_14_max', 'B_11-P_3_mean', 'B_26_std', 'D_69_mean', 'D_39/P_2_mean', 'S_20_std', 'D_82_std', 'D_39_last_3', 'D_118_last', 'B_39_mean', 'D_48_last_3', 'S_12_last', 'B_9_max', 'B_13_std', 'D_48_last_2', 'D_59_last_3', 'B_12_mean', 'D_75_last_3', 'D_121_last', 'B_20_last_3', 'R_6_std', 'D_84_last', 'R_10_mean', 'S_9_max', 'D_79_last', 'B_17_last_2', 'R_12_min', 'B_28_max', 'D_53_last', 'D_83_last', 'B_19_last', 'R_9_last_3', 'B_41_std', 'B_21_last_2', 'B_39_max', 'B_22_std', 'D_60_mean', 'B_25_last', 'D_74_last', 'B_36_mean', 'D_42_last_3', 'B_19_last_2', 'S_18_mean', 'D_72_mean', 'D_59_min', 'D_133_last_2', 'B_4_last_2', 'D_83_std', 'D_111_max', 'R_10_last', 'B_4_mean', 'D_53_last_3', 'D_102_last_2', 'S_23/P_3_mean', 'S_15_std', 'S_7_mean', 'B_32_last_2', 'B_21_last', 'D_46_last_3', 'D_55_last_3', 'D_91_mean', 'B_18_last_2', 'D_41_min', 'D_73_last_3', 'D_58_last', 'D_111_std', 'B_36_std', 'B_17/P_3_std', 'R_11_max', 'B_11-P_3_std', 'D_145_mean', 'D_118_std', 'D_61_last_3', 'D_58_last_3', 'S_11_last_2', 'D_42_std', 'B_41_last', 'S_17_std', 'D_102_last_3', 'D_80_std', 'S_13_std', 'B_39_last', 'D_108_last_2', 'S_25_last_3', 'D_124_mean', 'S_3_last_3', 'D_69_last_3', 'D_111_mean', 'B_39_last_3', 'D_69_last', 'S_16_last', 'D_140_last_3', 'D_39_mean', 'D_107_mean', 'B_36_max', 'S_26_min', 'D_69_last_2', 'D_134_mean', 'B_24_last_3', 'D_106_last_3', 'D_69_max', 'D_91_std', 'D_74_mean', 'B_26_max', 'D_144_min', 'B_17_last_3', 'B_6_last_2', 'B_23_min', 'B_24_mean', 'D_62_std', 'P_3_last_2', 'S_12_last_3', 'D_60_std', 'S_24_last_2', 'D_55_max', 'B_37_mean', 'D_102_last', 'B_1_max', 'B_8_std', 'D_110_min', 'B_9_last_2', 'D_133_min', 'D_61_max', 'S_7_min', 'D_48_mean', 'S_27_last_3', 'B_27_last_3', 'D_44_mean', 'B_6_max', 'D_108_std', 'R_14_std', 'B_36_last_2', 'B_26_last_3', 'R_20_last']
  cat_features:
  - B_30_last
  - B_38_last
  - D_114_last
  - D_116_last
  - D_117_last
  - D_120_last
  - D_126_last
  - D_63_last
  - D_64_last
  - D_66_last
  - D_68_last
  - B_30_last_2
  - B_38_last_2
  - D_114_last_2
  - D_116_last_2
  - D_117_last_2
  - D_120_last_2
  - D_126_last_2
  - D_63_last_2
  - D_64_last_2
  - D_66_last_2
  - D_68_last_2
  - B_30_last_3
  - B_38_last_3
  - D_114_last_3
  - D_116_last_3
  - D_117_last_3
  - D_120_last_3
  - D_126_last_3
  - D_63_last_3
  - D_64_last_3
  - D_66_last_3
  - D_68_last_3
  - B_30_nunique
  - B_38_nunique
  - D_114_nunique
  - D_116_nunique
  - D_117_nunique
  - D_120_nunique
  - D_126_nunique
  - D_63_nunique
  - D_64_nunique
  - D_66_nunique
  - D_68_nunique
  - B_30_count
  - B_38_count
  - D_114_count
  - D_116_count
  - D_117_count
  - D_120_count
  - D_126_count
  - D_63_count
  - D_64_count
  - D_66_count
  - D_68_count
  encoder: res/data/
experiment:
  project: amex-default-prediction
  entity: ds-wook
  name: lightgbm_dart_15
  tags: LightGBM-DART
model:
  fold: 10
  params:
    reg_alpha: 5.998770177220496e-05
    reg_lambda: 0.07127674208132959
    boosting_type: dart
    learning_rate: 0.03
    n_estimators: 3000
    objective: binary
    max_depth: 16
    num_leaves: 128
    colsample_bytree: 0.4241631237880101
    subsample: 0.8876057928391585
    subsample_freq: 5
    min_child_samples: 5
    max_bin: 449
  path: res/models/
  name: 10fold_lightgbm_pay_features_last.pkl
  early_stopping_rounds: 250
  search: False
  seed: 42
  verbose: 250