hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: input/amex-agg-data-f32/
  is_train: true
  target: target
  train: train_agg_f32.pkl
  test: test_agg_f32_part
  drop_features: customer_ID
  cat_features:
  - B_30_last
  - B_38_last
  - D_114_last
  - D_116_last
  - D_117_last
  - D_120_last
  - D_126_last
  - D_63_last
  - D_64_last
  - D_66_last
  - D_68_last
  encoder: res/data/
experiment:
  project: amex-default-prediction
  entity: ds-wook
  name: lightgbm_dart_6
  tags:
  - LightGBM
model:
  fold: 10
  params:
    reg_alpha: 5.998770177220496e-05
    reg_lambda: 0.07127674208132959
    boosting_type: dart
    learning_rate: 0.05
    n_estimators: 5000
    objective: cross_entropy
    max_depth: 16
    num_leaves: 128
    colsample_bytree: 0.4241631237880101
    subsample: 0.8876057928391585
    subsample_freq: 5
    min_child_samples: 5
    max_bin: 449
  path: res/models/
  name: 10fold_lightgbm_dart_trick_cross_entropy.pkl
  search: False
  seed: 42
  verbose: 100
