hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: input/amex-pay-features/
  is_train: true
  target: target
  train: train_pay_features.pkl
  test: test_pay_features
  drop_features: customer_ID
  cat_features:
  - B_30_last
  - B_38_last
  - D_114_last
  - D_116_last
  - D_117_last
  - D_120_last
  - D_126_last
  - D_63_last
  - D_64_last
  - D_66_last
  - D_68_last
  encoder: res/data/
experiment:
  project: amex-default-prediction
  entity: ds-wook
  name: xgboost_dart_1
model:
  fold: 10
  params:
    booster: dart
    colsample_bytree: 0.44442679104045424
    gamma: 0.07361716094628554
    learning_rate: 0.05
    max_depth: 2
    min_child_weight: 5
    n_estimators: 2500
    n_jobs: -1
    objective: binary:logistic
    reg_alpha: 0.3916028672163949
    reg_lambda: 0.8398892426801621
    subsample: 0.8708229999183839
  path: res/models/
  name: 10fold_xgboost_dart.pkl
  early_stopping_rounds: 200
  search: False
  seed: 42
  verbose: 500
