path: input/amex-trick-features/
target: target
train: train_pay_features.pkl
test: test_pay_features
drop_features: customer_ID
cat_features: 
- D_114_last
- D_117_last
- D_120_last
- D_63_last
- D_64_last
- D_66_last
encoder: res/data/
