path: input/amex-lag-features/
num: 5
seed: 42
target: target
train: train_lag_features
test: test_lag_features
drop_features:
- customer_ID
- S_2
cat_features:
- B_30_last
- B_38_last
- D_114_last
- D_116_last
- D_117_last
- D_120_last
- D_126_last
- D_63_last
- D_64_last
- D_66_last
- D_68_last
encoder: res/data/
