path: input/amex-lag-features/
target: target
train: train_lag_features.pkl
test: test_lag_features
drop_features: customer_ID
cat_features: 
- D_114_last
- D_117_last
- D_120_last
- D_63_last
- D_64_last
- D_66_last
encoder: res/data/
