path: input/amex-bruteforce-features/
num_train: 5
num_test: 10
seed: 42
target: target
train: train_bruteforce_features
test: test_bruteforce_features
drop_features:
- customer_ID
- S_2
- SDist_first
cat_features:
- B_30_last
- B_38_last
- D_114_last
- D_116_last
- D_117_last
- D_120_last
- D_126_last
- D_63_last
- D_64_last
- D_66_last
- D_68_last
encoder: res/data/
