model:
  early_stopping_rounds: 100
  verbose: False
  params:
    boosting_type: dart
    n_jobs: -1
    objective: binary
    seed: 42
    n_estimators:
    - 2500
    - 5000
    learning_rate:
    - 0.001
    - 0.1
    num_leaves:
    - 2
    - 400
    min_child_samples:
    - 1
    - 250
    feature_fraction:
    - 0.1
    - 1.0
    max_depth:
    - 1
    - 30 
    bagging_fraction:
    - 0.1
    - 1.0 
    min_split_gain:
    - 1e-08
    - 10
    bagging_freq:
    - 0
    - 70
    min_data_in_leaf:
    - 1
    - 400
    lambda_l1:
    - 1e-08
    - 50
    lambda_l2:
    - 0.00000001
    - 50