params:
  boosting_type: dart
  n_jobs: -1
  objective: binary
  seed:
  - 10
  - 10000
  n_estimators:
  - 2500
  - 5000
  learning_rate:
  - 0.001
  - 0.1
  num_leaves:
  - 2
  - 512
  feature_fraction:
  - 0.1
  - 1.0
  bagging_fraction:
  - 0.1
  - 1.0 
  bagging_freq:
  - 0
  - 70
  min_data_in_leaf:
  - 1
  - 400
  lambda_l1:
  - 0.00000001
  - 50
  lambda_l2:
  - 0.00000001
  - 50
early_stopping_rounds: 1500
num_boost_round: 10500
verbose: 500
search:
  trials: 100
  direction: maximize
  params: best_params.yaml
  study_name: Optuna Search
  path_name: config/model/tuning_lgbm.yaml
  sampler:
    type: tpe
    n_startup_trials: 15
    multivariate: true
    group: true
    constant_liar: true
  pruner:
    type: median
    n_startup_trials: 15
    n_warmup_steps: 3
    interval_steps: 4