hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: input/amex-default-prediction/
  target: target
  train: train_data.ftr
  test: test_data.ftr
  cat_features:
  - B_30
  - B_38
  - D_114
  - D_116
  - D_117
  - D_120
  - D_126
  - D_63
  - D_64
  - D_66
  - D_68
experiment:
  project: amex-default-prediction
  entity: ds-wook
  reinit: True
  name: optuna-search
model:
  early_stopping_rounds: 100
  verbose: False
  seed: 42
  select: lightgbm
  lightgbm:
    params:
      boosting_type: gbdt
      n_estimators: 10000
      n_jobs: -1
      objective: binary
      learning_rate:
      - 0.03
      - 0.1
      num_leaves:
      - 4
      - 64
      max_depth:
      - 4
      - 16 
      subsample:
      - 0.1
      - 1.0 
      colsample_bytree:
      - 0.1
      - 1.0 
      reg_alpha:
      - 0.01
      - 0.1 
      reg_lambda:
      - 0.01
      - 0.1
    xgboost:
      params:
        n_estimators: 10000
        n_jobs: -1
        objective: reg:squarederror
        random_state: 42
        colsample_bytree:
        - 0.4
        - 1.0
        gamma:
        - 0.01
        - 0.1
        learning_rate:
        - 0.001
        - 0.01
        max_depth:
        - 2
        - 10
        min_child_weight:
        - 3
        - 10
        reg_alpha:
        - 0.1
        - 0.5
        reg_lambda:
        - 0.3
        - 1.0
        subsample:
        - 0.3
        - 1.0
search:
  trials: 100
  direction: maximize
  params: best_params.yaml
  study_name: Optuna Search
  sampler:
    type: tpe
    n_startup_trials: 15
    multivariate: true
    group: true
    constant_liar: true
  pruner:
    type: hyperband
    min_resource: 3
    reduction_factor: 5
