model:
  early_stopping_rounds: 100
  verbose: False
  seed: 42
  params:
    n_estimators: 10000
    n_jobs: -1
    objective: binary:logistic
    random_state: 42
    colsample_bytree:
    - 0.4
    - 1.0
    gamma:
    - 0.01
    - 0.1
    learning_rate:
    - 0.001
    - 0.01
    max_depth:
    - 2
    - 10
    min_child_weight:
    - 3
    - 10
    reg_alpha:
    - 0.1
    - 0.5
    reg_lambda:
    - 0.3
    - 1.0
    subsample:
    - 0.3
    - 1.0